doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
        reports_cache_db:
            server: '%env(CACHE_MONGODB_URL)%'
            options: {}
    ## default_database: 
    document_managers:
        default:
            auto_mapping: true
            connection: default
            database: '%env(MONGODB_DB)%'
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: App\Document\
                    alias: App
        reports_cache_db:
            connection: reports_cache_db
            database: '%env(CACHE_MONGODB_REPORTS_DB)%'
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document/Reports'
                    prefix: App\Document\Reports\
                    alias: AppReport
