nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: [GET, OPTIONS, POST, PUT, DELETE]
        allow_headers: [Content-Type, Authorization, X-Switch-User]
        expose_headers: [Link]
        forced_allow_origin_value: '*'
        max_age: 3600
    paths:
        '^/': ~
