App\Entity\ActivitySmsHistory:
    attributes:
        id:
            groups:
                # -
        activity:
            groups:
                - activity_sms_history_read
                - activity_sms_history_write
        inboundSMS:
            groups:
                - activity_sms_history_read
                - activity_sms_history_write
        outboundSMS:
            groups:
                - activity_sms_history_read
                - activity_sms_history_write

        # TimestampableTrait
        dateCreated:
            groups:
                - activity_sms_history_read
        dateModified:
            groups:
                - activity_sms_history_read
