App\Entity\ApplicationRequestStatusHistory:
    attributes:
        dateCreated:
            groups:
                - application_request_read
        text:
            groups:
                - application_request_read
