App\Entity\ApplicationRequestListItem:
    attributes:
        item:
            groups:
                - list_item_read
                - application_request_list_item_read
                - application_request_list_item_write