App\Entity\EarnContractCreditsAction:
    attributes:
        instrument:
            groups:
                - earn_contract_credits_action_read
                - earn_contract_credits_action_write
                - update_credits_action_read
        object:
            groups:
                - earn_contract_credits_action_read
                - earn_contract_credits_action_write
                - update_credits_action_read
        scheme:
            groups:
                - earn_contract_credits_action_read
                - earn_contract_credits_action_write
                - update_credits_action_read
        sender:
            groups:
                - earn_contract_credits_action_read
                - earn_contract_credits_action_write
                - update_credits_action_read
