App\Entity\EmailCampaignSourceListItem:
    attributes:
        emailAddress:
            groups:
                - email_campaign_source_list_item_read
                - email_campaign_source_list_item_write
                - email_campaign_source_list_read
                - source_list_read
                - mailgun_bounce_event_read
                - mailgun_click_event_read
                - mailgun_complain_event_read
                - mailgun_deliver_event_read
                - mailgun_open_event_read
