App\Entity\ExpireCustomerCreditsAction:
    attributes:
        object:
            groups:
                - expire_customer_credits_action_read
                - expire_customer_credits_action_write
                - update_credits_action_read
        scheme:
            groups:
                - expire_customer_credits_action_read
                - expire_customer_credits_action_write
                - update_credits_action_read
