App\Entity\ListItem:
    attributes:
        id:
            groups:
                # -
        description:
            groups:
                - addon_service_list_item_read
                - addon_service_list_item_write
                - application_request_list_item_read
                - application_request_list_item_write
                - contract_form_read
                - customer_account_list_item_read
                - customer_account_list_item_write
                - direct_mail_campaign_source_list_item_read
                - direct_mail_campaign_source_list_item_write
                - direct_mail_campaign_source_list_read
                - email_campaign_source_list_item_read
                - email_campaign_source_list_item_write
                - email_campaign_source_list_read
                - free_gift_list_item_read
                - free_gift_list_item_write
                - lead_list_item_read
                - lead_list_item_write
                - list_item_read
                - list_item_write
                - offer_list_item_read
                - offer_list_item_write
                - security_deposit_list_item_read
                - security_deposit_list_item_write
                - sms_campaign_source_list_item_read
                - sms_campaign_source_list_item_write
                - sms_campaign_source_list_read
                - source_list_read
                - tariff_rate_list_item_read
                - tariff_rate_list_item_write
                - unsubscribe_list_item_read
                - unsubscribe_list_item_write
                - campaign_expectation_list_item_read
                - campaign_expectation_list_item_write
                - campaign_source_list_item_read
                - campaign_source_list_item_write
                - mailgun_bounce_event_read
                - mailgun_click_event_read
                - mailgun_complain_event_read
                - mailgun_deliver_event_read
                - mailgun_open_event_read
        name:
            groups:
                - addon_service_list_item_read
                - addon_service_list_item_write
                - application_request_list_item_read
                - application_request_list_item_write
                - contract_form_read
                - customer_account_list_item_read
                - customer_account_list_item_write
                - direct_mail_campaign_source_list_item_read
                - direct_mail_campaign_source_list_item_write
                - direct_mail_campaign_source_list_read
                - email_campaign_source_list_item_read
                - email_campaign_source_list_item_write
                - email_campaign_source_list_read
                - free_gift_list_item_read
                - free_gift_list_item_write
                - lead_list_item_read
                - lead_list_item_write
                - list_item_read
                - list_item_write
                - offer_list_item_read
                - offer_list_item_write
                - security_deposit_list_item_read
                - security_deposit_list_item_write
                - sms_campaign_source_list_item_read
                - sms_campaign_source_list_item_write
                - sms_campaign_source_list_read
                - source_list_read
                - tariff_rate_list_item_read
                - tariff_rate_list_item_write
                - unsubscribe_list_item_read
                - unsubscribe_list_item_write
                - campaign_expectation_list_item_read
                - campaign_expectation_list_item_write
                - campaign_source_list_item_read
                - campaign_source_list_item_write
                - mailgun_bounce_event_read
                - mailgun_click_event_read
                - mailgun_complain_event_read
                - mailgun_deliver_event_read
                - mailgun_open_event_read
        position:
            groups:
                - addon_service_list_item_read
                - addon_service_list_item_write
                - application_request_list_item_read
                - application_request_list_item_write
                - contract_form_read
                - customer_account_list_item_read
                - customer_account_list_item_write
                - direct_mail_campaign_source_list_item_read
                - direct_mail_campaign_source_list_item_write
                - direct_mail_campaign_source_list_read
                - email_campaign_source_list_item_read
                - email_campaign_source_list_item_write
                - email_campaign_source_list_read
                - free_gift_list_item_read
                - free_gift_list_item_write
                - lead_list_item_read
                - lead_list_item_write
                - list_item_read
                - list_item_write
                - offer_list_item_read
                - offer_list_item_write
                - security_deposit_list_item_read
                - security_deposit_list_item_write
                - sms_campaign_source_list_item_read
                - sms_campaign_source_list_item_write
                - sms_campaign_source_list_read
                - source_list_read
                - tariff_rate_list_item_read
                - tariff_rate_list_item_write
                - unsubscribe_list_item_read
                - unsubscribe_list_item_write
                - campaign_expectation_list_item_read
                - campaign_expectation_list_item_write
                - campaign_source_list_item_read
                - campaign_source_list_item_write
                - mailgun_bounce_event_read
                - mailgun_click_event_read
                - mailgun_complain_event_read
                - mailgun_deliver_event_read
                - mailgun_open_event_read
        value:
            groups:
                - addon_service_list_item_read
                - addon_service_list_item_write
                - application_request_list_item_read
                - application_request_list_item_write
                - contract_form_read
                - customer_account_list_item_read
                - customer_account_list_item_write
                - direct_mail_campaign_source_list_item_read
                - direct_mail_campaign_source_list_item_write
                - direct_mail_campaign_source_list_read
                - email_campaign_source_list_item_read
                - email_campaign_source_list_item_write
                - email_campaign_source_list_read
                - free_gift_list_item_read
                - free_gift_list_item_write
                - lead_list_item_read
                - lead_list_item_write
                - list_item_read
                - list_item_write
                - offer_list_item_read
                - offer_list_item_write
                - security_deposit_list_item_read
                - security_deposit_list_item_write
                - sms_campaign_source_list_item_read
                - sms_campaign_source_list_item_write
                - sms_campaign_source_list_read
                - source_list_read
                - tariff_rate_list_item_read
                - tariff_rate_list_item_write
                - unsubscribe_list_item_read
                - unsubscribe_list_item_write
                - campaign_expectation_list_item_read
                - campaign_expectation_list_item_write
                - campaign_source_list_item_read
                - campaign_source_list_item_write
                - mailgun_bounce_event_read
                - mailgun_click_event_read
                - mailgun_complain_event_read
                - mailgun_deliver_event_read
                - mailgun_open_event_read
