App\Entity\MoneyCreditsTransaction:
    attributes:
        amount:
            groups:
                - credits_transaction_read
                - money_credits_transaction_read
                - money_credits_transaction_write
        balance:
            groups:
                - credits_transaction_read
                - money_credits_transaction_read
                - money_credits_transaction_write
        payments:
            groups:
                - credits_transaction_read
                - money_credits_transaction_read
                - money_credits_transaction_write
