App\Entity\QuantitativeValue:
    attributes:
        maxValue:
            groups:
                - affiliate_program_transaction_fetch_history_read
                - affiliate_program_transaction_fetch_history_write
                - affiliate_program_transaction_read
                - affiliate_program_transaction_write
                - application_request_read
                - application_request_write
                - contract_billing_summary_read
                - contract_consumption_history_read
                - contract_duration_read
                - contract_duration_write
                - contract_financial_history_read
                - contract_read
                - contract_write
                - credits_configuration_read
                - credits_configuration_write
                - credits_scheme_read
                - credits_scheme_write
                - customer_account_read
                - lead_read
                - lead_write
                - offer_list_item_read
                - offer_list_item_write
                - order_item_read
                - order_item_write
                - partner_read
                - partner_write
                - point_credits_transaction_read
                - point_credits_transaction_write
                - price_configuration_read
                - price_configuration_write
                - promotion_read
                - promotion_write
                - quotation_price_configuration_read
                - quotation_price_configuration_write
                - quotation_read
                - quotation_write
                - referral_credits_scheme_read
                - referral_credits_scheme_write
                - service_level_agreement_read
                - service_level_agreement_write
                - tariff_daily_rate_read
                - tariff_daily_rate_write
                - tariff_rate_read
                - tariff_rate_write
                - third_party_charge_configuration_read
                - third_party_charge_configuration_write
                - third_party_charge_read
                - third_party_charge_write
        minValue:
            groups:
                - affiliate_program_transaction_fetch_history_read
                - affiliate_program_transaction_fetch_history_write
                - affiliate_program_transaction_read
                - affiliate_program_transaction_write
                - application_request_read
                - application_request_write
                - contract_billing_summary_read
                - contract_consumption_history_read
                - contract_duration_read
                - contract_duration_write
                - contract_financial_history_read
                - contract_read
                - contract_write
                - credits_configuration_read
                - credits_configuration_write
                - credits_scheme_read
                - credits_scheme_write
                - customer_account_read
                - lead_read
                - lead_write
                - offer_list_item_read
                - offer_list_item_write
                - order_item_read
                - order_item_write
                - partner_read
                - partner_write
                - point_credits_transaction_read
                - point_credits_transaction_write
                - price_configuration_read
                - price_configuration_write
                - promotion_read
                - promotion_write
                - quotation_price_configuration_read
                - quotation_price_configuration_write
                - quotation_read
                - quotation_write
                - referral_credits_scheme_read
                - referral_credits_scheme_write
                - service_level_agreement_read
                - service_level_agreement_write
                - tariff_daily_rate_read
                - tariff_daily_rate_write
                - tariff_rate_read
                - tariff_rate_write
                - third_party_charge_configuration_read
                - third_party_charge_configuration_write
                - third_party_charge_read
                - third_party_charge_write
        unitCode:
            groups:
                - affiliate_program_transaction_fetch_history_read
                - affiliate_program_transaction_fetch_history_write
                - affiliate_program_transaction_read
                - affiliate_program_transaction_write
                - application_request_read
                - application_request_write
                - contract_billing_summary_read
                - contract_consumption_history_read
                - contract_duration_read
                - contract_duration_write
                - contract_financial_history_read
                - contract_form_read
                - contract_read
                - contract_write
                - credits_configuration_read
                - credits_configuration_write
                - credits_scheme_read
                - credits_scheme_write
                - customer_account_read
                - lead_read
                - lead_write
                - offer_list_item_read
                - offer_list_item_write
                - order_item_read
                - order_item_write
                - partner_read
                - partner_write
                - point_credits_transaction_read
                - point_credits_transaction_write
                - price_configuration_read
                - price_configuration_write
                - promotion_read
                - promotion_write
                - quotation_price_configuration_read
                - quotation_price_configuration_write
                - quotation_read
                - quotation_write
                - referral_credits_scheme_read
                - referral_credits_scheme_write
                - service_level_agreement_read
                - service_level_agreement_write
                - tariff_daily_rate_read
                - tariff_daily_rate_write
                - tariff_rate_read
                - tariff_rate_write
                - third_party_charge_configuration_read
                - third_party_charge_configuration_write
                - third_party_charge_read
                - third_party_charge_write
        value:
            groups:
                - affiliate_program_transaction_fetch_history_read
                - affiliate_program_transaction_fetch_history_write
                - affiliate_program_transaction_read
                - affiliate_program_transaction_write
                - application_request_read
                - application_request_write
                - contract_billing_summary_read
                - contract_consumption_history_read
                - contract_duration_read
                - contract_duration_write
                - contract_financial_history_read
                - contract_form_read
                - contract_read
                - contract_write
                - credits_configuration_read
                - credits_configuration_write
                - credits_scheme_read
                - credits_scheme_write
                - customer_account_read
                - lead_read
                - lead_write
                - offer_list_item_read
                - offer_list_item_write
                - order_item_read
                - order_item_write
                - partner_read
                - partner_write
                - point_credits_transaction_read
                - point_credits_transaction_write
                - price_configuration_read
                - price_configuration_write
                - promotion_read
                - promotion_write
                - quotation_price_configuration_read
                - quotation_price_configuration_write
                - quotation_read
                - quotation_write
                - referral_credits_scheme_read
                - referral_credits_scheme_write
                - service_level_agreement_read
                - service_level_agreement_write
                - tariff_daily_rate_read
                - tariff_daily_rate_write
                - tariff_rate_read
                - tariff_rate_write
                - third_party_charge_configuration_read
                - third_party_charge_configuration_write
                - third_party_charge_read
                - third_party_charge_write
