App\Entity\SmsHistory:
    attributes:
        id:
            groups:
                # -
        dateReceived:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write
        dateSent:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write
        direction:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write
        message:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write
        provider:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write
        rawMessage:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write
        recipientMobileNumber:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write
        sender:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write
        senderMobileNumber:
            groups:
                - activity_sms_history_read
                - sms_history_read
                - sms_history_write

        # TimestampableTrait
        dateCreated:
            groups:
                - activity_sms_history_read
                - sms_history_read
        dateModified:
            groups:
                - activity_sms_history_read
                - sms_history_read
