<?php

declare(strict_types=1);

namespace App\WebService\Billing\Enum;

class DownloadFileType
{
    const ACCOUNT_CLOSURE = 'ACCOUNT_CLOSURE';
    const CONTRACT_APPLICATION = 'CONTRACT_APPLICATION';
    const CONTRACT_APPLICATION_RETURN = 'CONTRACT_APPLICATION_RETURN';
    const CONTRACT_RENEWAL_APPLICATION = 'CONTRACT_RENEWAL_APPLICATION';
    const CUSTOMER_BLACKLIST = 'CUSTOMER_BLACKLIST';
    const EVENT_ACTIVITY = 'EVENT_ACTIVITY';
    const EXISTING_CUSTOMER_REFUND_RETURN = 'EXISTING_CUSTOMER_REFUND_RETURN';
    const GIRO_TERMINATION = 'GIRO_TERMINATION';
    const MASS_ACCOUNT_CLOSURE = 'MASS_ACCOUNT_CLOSURE';
    const MASS_ACCOUNT_TRANSFER_OUT = 'MASS_ACCOUNT_TRANSFER_OUT';
    const MASS_CONTRACT_APPLICATION = 'MASS_CONTRACT_APPLICATION';
    const MASS_CONTRACT_APPLICATION_RENEWAL = 'MASS_CONTRACT_APPLICATION_RENEWAL';
    const NONEXISTING_CUSTOMER_REFUND_RETURN = 'NONEXISTING_CUSTOMER_REFUND_RETURN';
    const PROMOTION_CODE = 'PROMOTION_CODE';
    const RCCS_TERMINATION = 'RCCS_TERMINATION';
    const TRANSFER_OUT = 'TRANSFER_OUT';
}
