<?php

declare(strict_types=1);

namespace App\WebService\Billing\Enum;

class UploadFileType
{
    const ACCOUNT_CLOSURE = 'ACCOUNT_CLOSURE';
    const ACCOUNT_CLOSURE_RETURN = 'ACCOUNT_CLOSURE_RETURN';
    const BILL_REDEMPTION = 'BILL_REDEMPTION';
    const CONTRACT_APPLICATION = 'CONTRACT_APPLICATION';
    const CONTRACT_APPLICATION_CUTOFF_LEFTOVER = 'CONTRACT_APPLICATION_CUTOFF_LEFTOVER';
    const CONTRACT_APPLICATION_RETURN = 'CONTRACT_APPLICATION_RETURN';
    const CONTRACT_RENEWAL_APPLICATION_RETURN = 'CONTRACT_RENEWAL_APPLICATION_RETURN';
    const EXISTING_CUSTOMER_REFUND = 'EXISTING_CUSTOMER_REFUND';
    const GIRO_TERMINATION = 'GIRO_TERMINATION';
    const NON_EXISTING_CUSTOMER_REFUND = 'NON_EXISTING_CUSTOMER_REFUND';
    const RCCS_TERMINATION = 'RCCS_TERMINATION';
    const TRANSFER_OUT = 'TRANSFER_OUT';
    const TRANSFER_OUT_RETURN = 'TRANSFER_OUT_RETURN';
}
