parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(S3_DOCUMENT_URI_PREFIX): ''
    
vich_uploader:
    mappings:
        file:
            uri_prefix: '%env(S3_DOCUMENT_URI_PREFIX)%'
        internal_file:
            uri_prefix: '%env(S3_DOCUMENT_URI_PREFIX)%'
