<?php

declare(strict_types=1);

namespace App\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20180713121801 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE update_credits_actions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE offer_categories_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE credits_configurations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE credits_transactions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE credits_schemes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE offer_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE orders_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE offers_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE order_items_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE credits_categories_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE update_credits_actions (id INT NOT NULL, credits_transaction_id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, amount NUMERIC(19, 4) DEFAULT NULL, currency VARCHAR(3) DEFAULT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(254) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, entity_type VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_97094AEE4353CA4D ON update_credits_actions (credits_transaction_id)');
        $this->addSql('CREATE INDEX IDX_97094AEE3414710B ON update_credits_actions (agent_id)');
        $this->addSql('CREATE INDEX IDX_97094AEE61220EA6 ON update_credits_actions (creator_id)');
        $this->addSql('COMMENT ON COLUMN update_credits_actions.status IS \'(DC2Type:action_status_enum)\'');
        $this->addSql('CREATE TABLE transfer_credits_actions (id INT NOT NULL, object_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_69BEDAA1232D562B ON transfer_credits_actions (object_id)');
        $this->addSql('CREATE TABLE offer_categories (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, description TEXT DEFAULT NULL, name TEXT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A65985BC3414710B ON offer_categories (agent_id)');
        $this->addSql('CREATE INDEX IDX_A65985BC61220EA6 ON offer_categories (creator_id)');
        $this->addSql('CREATE TABLE contracts_point_credits_actions (contract_id INT NOT NULL, point_credits_action_id INT NOT NULL, PRIMARY KEY(contract_id, point_credits_action_id))');
        $this->addSql('CREATE INDEX IDX_D9F788812576E0FD ON contracts_point_credits_actions (contract_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D9F78881900365A0 ON contracts_point_credits_actions (point_credits_action_id)');
        $this->addSql('CREATE TABLE credits_configurations (id INT NOT NULL, category_id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, description TEXT DEFAULT NULL, name TEXT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_period_max_value NUMERIC(19, 4) DEFAULT NULL, valid_period_min_value NUMERIC(19, 4) DEFAULT NULL, valid_period_unit_code TEXT DEFAULT NULL, valid_period_value NUMERIC(19, 4) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6F8F6B9B12469DE2 ON credits_configurations (category_id)');
        $this->addSql('CREATE INDEX IDX_6F8F6B9B3414710B ON credits_configurations (agent_id)');
        $this->addSql('CREATE INDEX IDX_6F8F6B9B61220EA6 ON credits_configurations (creator_id)');
        $this->addSql('CREATE TABLE earn_contract_credits_actions (id INT NOT NULL, object_id INT NOT NULL, scheme_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B617BE0C232D562B ON earn_contract_credits_actions (object_id)');
        $this->addSql('CREATE INDEX IDX_B617BE0C65797862 ON earn_contract_credits_actions (scheme_id)');
        $this->addSql('CREATE TABLE redeem_credits_actions (id INT NOT NULL, instrument_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FA9E49E2CF11D9C ON redeem_credits_actions (instrument_id)');
        $this->addSql('CREATE TABLE credits_transactions (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, credits_transaction_number TEXT NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, entity_type VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C14DCC843414710B ON credits_transactions (agent_id)');
        $this->addSql('CREATE INDEX IDX_C14DCC8461220EA6 ON credits_transactions (creator_id)');
        $this->addSql('CREATE INDEX IDX_C14DCC84CE5A633F ON credits_transactions (credits_transaction_number)');
        $this->addSql('CREATE TABLE money_credits_transactions (id INT NOT NULL, amount_currency VARCHAR(3) DEFAULT NULL, amount_value NUMERIC(19, 4) DEFAULT NULL, balance_currency VARCHAR(3) DEFAULT NULL, balance_value NUMERIC(19, 4) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CBE4C41E3271B7EA ON money_credits_transactions (amount_value)');
        $this->addSql('CREATE INDEX IDX_CBE4C41E8301E966 ON money_credits_transactions (balance_value)');
        $this->addSql('CREATE TABLE credits_schemes (id INT NOT NULL, configuration_id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, scheme_id TEXT DEFAULT NULL, type VARCHAR(254) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, amount_max_value NUMERIC(19, 4) DEFAULT NULL, amount_min_value NUMERIC(19, 4) DEFAULT NULL, amount_unit_code TEXT DEFAULT NULL, amount_value NUMERIC(19, 4) DEFAULT NULL, monetary_exchange_value_currency VARCHAR(3) DEFAULT NULL, monetary_exchange_value_value NUMERIC(19, 4) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_41D99D6273F32DD8 ON credits_schemes (configuration_id)');
        $this->addSql('CREATE INDEX IDX_41D99D623414710B ON credits_schemes (agent_id)');
        $this->addSql('CREATE INDEX IDX_41D99D6261220EA6 ON credits_schemes (creator_id)');
        $this->addSql('COMMENT ON COLUMN credits_schemes.type IS \'(DC2Type:credits_type_enum)\'');
        $this->addSql('CREATE TABLE offer_types (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, description TEXT DEFAULT NULL, name TEXT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DA1DF4D93414710B ON offer_types (agent_id)');
        $this->addSql('CREATE INDEX IDX_DA1DF4D961220EA6 ON offer_types (creator_id)');
        $this->addSql('CREATE TABLE offer_catalogs (id INT NOT NULL, remarks TEXT DEFAULT NULL, status VARCHAR(254) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN offer_catalogs.status IS \'(DC2Type:catalog_status_enum)\'');
        $this->addSql('CREATE TABLE point_credits_transactions (id INT NOT NULL, amount_max_value NUMERIC(19, 4) DEFAULT NULL, amount_min_value NUMERIC(19, 4) DEFAULT NULL, amount_unit_code TEXT DEFAULT NULL, amount_value NUMERIC(19, 4) DEFAULT NULL, balance_max_value NUMERIC(19, 4) DEFAULT NULL, balance_min_value NUMERIC(19, 4) DEFAULT NULL, balance_unit_code TEXT DEFAULT NULL, balance_value NUMERIC(19, 4) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4C981E3F3271B7EA ON point_credits_transactions (amount_value)');
        $this->addSql('CREATE INDEX IDX_4C981E3F8301E966 ON point_credits_transactions (balance_value)');
        $this->addSql('CREATE TABLE orders (id INT NOT NULL, customer_id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, order_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_number VARCHAR(255) NOT NULL, order_status VARCHAR(254) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E52FFDEE9395C3F3 ON orders (customer_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE3414710B ON orders (agent_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE61220EA6 ON orders (creator_id)');
        $this->addSql('COMMENT ON COLUMN orders.order_status IS \'(DC2Type:order_status_enum)\'');
        $this->addSql('CREATE TABLE offer_list_items (id INT NOT NULL, item_id INT NOT NULL, serial_number TEXT DEFAULT NULL, status TEXT NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inventory_level_max_value NUMERIC(19, 4) DEFAULT NULL, inventory_level_min_value NUMERIC(19, 4) DEFAULT NULL, inventory_level_unit_code TEXT DEFAULT NULL, inventory_level_value NUMERIC(19, 4) DEFAULT NULL, monetary_exchange_value_currency VARCHAR(3) DEFAULT NULL, monetary_exchange_value_value NUMERIC(19, 4) DEFAULT NULL, price_max_price NUMERIC(19, 4) DEFAULT NULL, price_min_price NUMERIC(19, 4) DEFAULT NULL, price_price NUMERIC(19, 4) DEFAULT NULL, price_price_currency VARCHAR(3) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A427BE9A126F525E ON offer_list_items (item_id)');
        $this->addSql('CREATE TABLE offers (id INT NOT NULL, category_id INT NOT NULL, image_id INT NOT NULL, type_id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, description TEXT NOT NULL, name TEXT NOT NULL, seller TEXT NOT NULL, sku TEXT NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DA46042712469DE2 ON offers (category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DA4604273DA5256D ON offers (image_id)');
        $this->addSql('CREATE INDEX IDX_DA460427C54C8C93 ON offers (type_id)');
        $this->addSql('CREATE INDEX IDX_DA4604273414710B ON offers (agent_id)');
        $this->addSql('CREATE INDEX IDX_DA46042761220EA6 ON offers (creator_id)');
        $this->addSql('CREATE TABLE expire_customer_credits_actions (id INT NOT NULL, object_id INT NOT NULL, scheme_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E82331DE232D562B ON expire_customer_credits_actions (object_id)');
        $this->addSql('CREATE INDEX IDX_E82331DE65797862 ON expire_customer_credits_actions (scheme_id)');
        $this->addSql('CREATE TABLE earn_customer_credits_actions (id INT NOT NULL, object_id INT NOT NULL, scheme_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1E61856C232D562B ON earn_customer_credits_actions (object_id)');
        $this->addSql('CREATE INDEX IDX_1E61856C65797862 ON earn_customer_credits_actions (scheme_id)');
        $this->addSql('CREATE TABLE customer_accounts_money_credits_actions (customer_account_id INT NOT NULL, money_credits_action_id INT NOT NULL, PRIMARY KEY(customer_account_id, money_credits_action_id))');
        $this->addSql('CREATE INDEX IDX_D00752C166A25B38 ON customer_accounts_money_credits_actions (customer_account_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D00752C166596692 ON customer_accounts_money_credits_actions (money_credits_action_id)');
        $this->addSql('CREATE TABLE customer_accounts_point_credits_actions (customer_account_id INT NOT NULL, point_credits_action_id INT NOT NULL, PRIMARY KEY(customer_account_id, point_credits_action_id))');
        $this->addSql('CREATE INDEX IDX_9665954966A25B38 ON customer_accounts_point_credits_actions (customer_account_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_96659549900365A0 ON customer_accounts_point_credits_actions (point_credits_action_id)');
        $this->addSql('CREATE TABLE order_items (id INT NOT NULL, offer_id INT NOT NULL, order_id INT NOT NULL, order_item_number VARCHAR(255) DEFAULT NULL, order_item_status VARCHAR(255) DEFAULT NULL, order_quantity_max_value NUMERIC(19, 4) DEFAULT NULL, order_quantity_min_value NUMERIC(19, 4) DEFAULT NULL, order_quantity_unit_code TEXT DEFAULT NULL, order_quantity_value NUMERIC(19, 4) DEFAULT NULL, unit_price_max_price NUMERIC(19, 4) DEFAULT NULL, unit_price_min_price NUMERIC(19, 4) DEFAULT NULL, unit_price_price NUMERIC(19, 4) DEFAULT NULL, unit_price_price_currency VARCHAR(3) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_62809DB053C674EE ON order_items (offer_id)');
        $this->addSql('CREATE INDEX IDX_62809DB08D9F6D38 ON order_items (order_id)');
        $this->addSql('CREATE TABLE expire_contract_credits_actions (id INT NOT NULL, object_id INT NOT NULL, scheme_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_40550ABE232D562B ON expire_contract_credits_actions (object_id)');
        $this->addSql('CREATE INDEX IDX_40550ABE65797862 ON expire_contract_credits_actions (scheme_id)');
        $this->addSql('CREATE TABLE allocate_credits_actions (id INT NOT NULL, object_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_232D940B232D562B ON allocate_credits_actions (object_id)');
        $this->addSql('CREATE TABLE credits_categories (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, description TEXT DEFAULT NULL, name TEXT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_68A9C6593414710B ON credits_categories (agent_id)');
        $this->addSql('CREATE INDEX IDX_68A9C65961220EA6 ON credits_categories (creator_id)');
        $this->addSql('ALTER TABLE update_credits_actions ADD CONSTRAINT FK_97094AEE4353CA4D FOREIGN KEY (credits_transaction_id) REFERENCES credits_transactions (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE update_credits_actions ADD CONSTRAINT FK_97094AEE3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE update_credits_actions ADD CONSTRAINT FK_97094AEE61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transfer_credits_actions ADD CONSTRAINT FK_69BEDAA1232D562B FOREIGN KEY (object_id) REFERENCES customer_accounts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transfer_credits_actions ADD CONSTRAINT FK_69BEDAA1BF396750 FOREIGN KEY (id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_categories ADD CONSTRAINT FK_A65985BC3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_categories ADD CONSTRAINT FK_A65985BC61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_point_credits_actions ADD CONSTRAINT FK_D9F788812576E0FD FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_point_credits_actions ADD CONSTRAINT FK_D9F78881900365A0 FOREIGN KEY (point_credits_action_id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_configurations ADD CONSTRAINT FK_6F8F6B9B12469DE2 FOREIGN KEY (category_id) REFERENCES credits_categories (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_configurations ADD CONSTRAINT FK_6F8F6B9B3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_configurations ADD CONSTRAINT FK_6F8F6B9B61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE earn_contract_credits_actions ADD CONSTRAINT FK_B617BE0C232D562B FOREIGN KEY (object_id) REFERENCES contracts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE earn_contract_credits_actions ADD CONSTRAINT FK_B617BE0C65797862 FOREIGN KEY (scheme_id) REFERENCES credits_schemes (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE earn_contract_credits_actions ADD CONSTRAINT FK_B617BE0CBF396750 FOREIGN KEY (id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE redeem_credits_actions ADD CONSTRAINT FK_FA9E49E2CF11D9C FOREIGN KEY (instrument_id) REFERENCES orders (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE redeem_credits_actions ADD CONSTRAINT FK_FA9E49E2BF396750 FOREIGN KEY (id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_transactions ADD CONSTRAINT FK_C14DCC843414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_transactions ADD CONSTRAINT FK_C14DCC8461220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE money_credits_transactions ADD CONSTRAINT FK_CBE4C41EBF396750 FOREIGN KEY (id) REFERENCES credits_transactions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_schemes ADD CONSTRAINT FK_41D99D6273F32DD8 FOREIGN KEY (configuration_id) REFERENCES credits_configurations (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_schemes ADD CONSTRAINT FK_41D99D623414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_schemes ADD CONSTRAINT FK_41D99D6261220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_types ADD CONSTRAINT FK_DA1DF4D93414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_types ADD CONSTRAINT FK_DA1DF4D961220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_catalogs ADD CONSTRAINT FK_8AD08768BF396750 FOREIGN KEY (id) REFERENCES item_lists (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE point_credits_transactions ADD CONSTRAINT FK_4C981E3FBF396750 FOREIGN KEY (id) REFERENCES credits_transactions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer_accounts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_list_items ADD CONSTRAINT FK_A427BE9A126F525E FOREIGN KEY (item_id) REFERENCES offers (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_list_items ADD CONSTRAINT FK_A427BE9ABF396750 FOREIGN KEY (id) REFERENCES list_items (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA46042712469DE2 FOREIGN KEY (category_id) REFERENCES offer_categories (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA4604273DA5256D FOREIGN KEY (image_id) REFERENCES digital_documents (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA460427C54C8C93 FOREIGN KEY (type_id) REFERENCES offer_types (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA4604273414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA46042761220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expire_customer_credits_actions ADD CONSTRAINT FK_E82331DE232D562B FOREIGN KEY (object_id) REFERENCES customer_accounts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expire_customer_credits_actions ADD CONSTRAINT FK_E82331DE65797862 FOREIGN KEY (scheme_id) REFERENCES credits_schemes (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expire_customer_credits_actions ADD CONSTRAINT FK_E82331DEBF396750 FOREIGN KEY (id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE earn_customer_credits_actions ADD CONSTRAINT FK_1E61856C232D562B FOREIGN KEY (object_id) REFERENCES customer_accounts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE earn_customer_credits_actions ADD CONSTRAINT FK_1E61856C65797862 FOREIGN KEY (scheme_id) REFERENCES credits_schemes (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE earn_customer_credits_actions ADD CONSTRAINT FK_1E61856CBF396750 FOREIGN KEY (id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts_money_credits_actions ADD CONSTRAINT FK_D00752C166A25B38 FOREIGN KEY (customer_account_id) REFERENCES customer_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts_money_credits_actions ADD CONSTRAINT FK_D00752C166596692 FOREIGN KEY (money_credits_action_id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts_point_credits_actions ADD CONSTRAINT FK_9665954966A25B38 FOREIGN KEY (customer_account_id) REFERENCES customer_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts_point_credits_actions ADD CONSTRAINT FK_96659549900365A0 FOREIGN KEY (point_credits_action_id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB053C674EE FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB08D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expire_contract_credits_actions ADD CONSTRAINT FK_40550ABE232D562B FOREIGN KEY (object_id) REFERENCES contracts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expire_contract_credits_actions ADD CONSTRAINT FK_40550ABE65797862 FOREIGN KEY (scheme_id) REFERENCES credits_schemes (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expire_contract_credits_actions ADD CONSTRAINT FK_40550ABEBF396750 FOREIGN KEY (id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allocate_credits_actions ADD CONSTRAINT FK_232D940B232D562B FOREIGN KEY (object_id) REFERENCES contracts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allocate_credits_actions ADD CONSTRAINT FK_232D940BBF396750 FOREIGN KEY (id) REFERENCES update_credits_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_categories ADD CONSTRAINT FK_68A9C6593414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credits_categories ADD CONSTRAINT FK_68A9C65961220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE transfer_credits_actions DROP CONSTRAINT FK_69BEDAA1BF396750');
        $this->addSql('ALTER TABLE contracts_point_credits_actions DROP CONSTRAINT FK_D9F78881900365A0');
        $this->addSql('ALTER TABLE earn_contract_credits_actions DROP CONSTRAINT FK_B617BE0CBF396750');
        $this->addSql('ALTER TABLE redeem_credits_actions DROP CONSTRAINT FK_FA9E49E2BF396750');
        $this->addSql('ALTER TABLE expire_customer_credits_actions DROP CONSTRAINT FK_E82331DEBF396750');
        $this->addSql('ALTER TABLE earn_customer_credits_actions DROP CONSTRAINT FK_1E61856CBF396750');
        $this->addSql('ALTER TABLE customer_accounts_money_credits_actions DROP CONSTRAINT FK_D00752C166596692');
        $this->addSql('ALTER TABLE customer_accounts_point_credits_actions DROP CONSTRAINT FK_96659549900365A0');
        $this->addSql('ALTER TABLE expire_contract_credits_actions DROP CONSTRAINT FK_40550ABEBF396750');
        $this->addSql('ALTER TABLE allocate_credits_actions DROP CONSTRAINT FK_232D940BBF396750');
        $this->addSql('ALTER TABLE offers DROP CONSTRAINT FK_DA46042712469DE2');
        $this->addSql('ALTER TABLE credits_schemes DROP CONSTRAINT FK_41D99D6273F32DD8');
        $this->addSql('ALTER TABLE update_credits_actions DROP CONSTRAINT FK_97094AEE4353CA4D');
        $this->addSql('ALTER TABLE money_credits_transactions DROP CONSTRAINT FK_CBE4C41EBF396750');
        $this->addSql('ALTER TABLE point_credits_transactions DROP CONSTRAINT FK_4C981E3FBF396750');
        $this->addSql('ALTER TABLE earn_contract_credits_actions DROP CONSTRAINT FK_B617BE0C65797862');
        $this->addSql('ALTER TABLE expire_customer_credits_actions DROP CONSTRAINT FK_E82331DE65797862');
        $this->addSql('ALTER TABLE earn_customer_credits_actions DROP CONSTRAINT FK_1E61856C65797862');
        $this->addSql('ALTER TABLE expire_contract_credits_actions DROP CONSTRAINT FK_40550ABE65797862');
        $this->addSql('ALTER TABLE offers DROP CONSTRAINT FK_DA460427C54C8C93');
        $this->addSql('ALTER TABLE redeem_credits_actions DROP CONSTRAINT FK_FA9E49E2CF11D9C');
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT FK_62809DB08D9F6D38');
        $this->addSql('ALTER TABLE offer_list_items DROP CONSTRAINT FK_A427BE9A126F525E');
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT FK_62809DB053C674EE');
        $this->addSql('ALTER TABLE credits_configurations DROP CONSTRAINT FK_6F8F6B9B12469DE2');
        $this->addSql('DROP SEQUENCE update_credits_actions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE offer_categories_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE credits_configurations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE credits_transactions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE credits_schemes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE offer_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE orders_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE offers_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE order_items_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE credits_categories_id_seq CASCADE');
        $this->addSql('DROP TABLE update_credits_actions');
        $this->addSql('DROP TABLE transfer_credits_actions');
        $this->addSql('DROP TABLE offer_categories');
        $this->addSql('DROP TABLE contracts_point_credits_actions');
        $this->addSql('DROP TABLE credits_configurations');
        $this->addSql('DROP TABLE earn_contract_credits_actions');
        $this->addSql('DROP TABLE redeem_credits_actions');
        $this->addSql('DROP TABLE credits_transactions');
        $this->addSql('DROP TABLE money_credits_transactions');
        $this->addSql('DROP TABLE credits_schemes');
        $this->addSql('DROP TABLE offer_types');
        $this->addSql('DROP TABLE offer_catalogs');
        $this->addSql('DROP TABLE point_credits_transactions');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE offer_list_items');
        $this->addSql('DROP TABLE offers');
        $this->addSql('DROP TABLE expire_customer_credits_actions');
        $this->addSql('DROP TABLE earn_customer_credits_actions');
        $this->addSql('DROP TABLE customer_accounts_money_credits_actions');
        $this->addSql('DROP TABLE customer_accounts_point_credits_actions');
        $this->addSql('DROP TABLE order_items');
        $this->addSql('DROP TABLE expire_contract_credits_actions');
        $this->addSql('DROP TABLE allocate_credits_actions');
        $this->addSql('DROP TABLE credits_categories');
    }
}
