<?php

declare(strict_types=1);

namespace App\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190925092802 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE customer_blacklist_configurations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE customer_blacklist_configurations (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, action VARCHAR(254) NOT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_783E2C9B3414710B ON customer_blacklist_configurations (agent_id)');
        $this->addSql('CREATE INDEX IDX_783E2C9B61220EA6 ON customer_blacklist_configurations (creator_id)');
        $this->addSql('COMMENT ON COLUMN customer_blacklist_configurations.action IS \'(DC2Type:blacklist_configuration_action_enum)\'');
        $this->addSql('ALTER TABLE customer_blacklist_configurations ADD CONSTRAINT FK_783E2C9B3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_blacklist_configurations ADD CONSTRAINT FK_783E2C9B61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('DROP SEQUENCE customer_blacklist_configurations_id_seq CASCADE');
        $this->addSql('DROP TABLE customer_blacklist_configurations');
    }

    public function postUp(Schema $schema): void
    {
        parent::postUp($schema); // TODO: Change the autogenerated stub

        $this->connection->executeQuery("INSERT INTO customer_blacklist_configurations (id,action, description, enabled) VALUES (1,'CREATE_USER', 'Check for blacklisted customers while registering for SSP', false), 
(2,'BILL_REBATE_REDEMPTION', 'To check for blacklist customer while redeeming bill rebate', false), (3,'CONTACT_PERSON_SUBMIT_APPLICATION', 'To check for blacklist contact person while submitting application request', false),
(4,'CUSTOMER_SUBMIT_APPLICATION', 'To check for blacklist customer while submitting application request', true),(5,'REDEMPTION', 'To check for blacklist customer while redemption', true) ");
    }
}
