<?php

declare(strict_types=1);

namespace App\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

class Version20180306101851 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE activities_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE partners_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE employee_roles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tariff_rates_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contracts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE application_requests_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE leads_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contact_points_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contract_actions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE postal_addresses_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE digital_documents_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE phone_number_roles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE people_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE commission_rates_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE web_pages_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE corporations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE customer_account_postal_addresses_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE customer_accounts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE customer_account_relationships_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE notes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE identifications_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE activities (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, text TEXT DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, entity_type VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B5F1AFE53414710B ON activities (agent_id)');
        $this->addSql('CREATE INDEX IDX_B5F1AFE561220EA6 ON activities (creator_id)');
        $this->addSql('CREATE INDEX IDX_B5F1AFE58BDAB045 ON activities (date_created)');
        $this->addSql('CREATE TABLE sms_activities (id INT NOT NULL, recipient_mobile_number VARCHAR(35) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN sms_activities.recipient_mobile_number IS \'(DC2Type:phone_number)\'');
        $this->addSql('CREATE TABLE partners (id INT NOT NULL, administrator_id INT DEFAULT NULL, announcement_audiences JSONB NOT NULL, joining_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, payout_start_date DATE DEFAULT NULL, termination_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, payout_cycle_max_value SMALLINT DEFAULT NULL, payout_cycle_min_value SMALLINT DEFAULT NULL, payout_cycle_unit_code TEXT DEFAULT NULL, payout_cycle_value SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EFEB51644B09E92C ON partners (administrator_id)');
        $this->addSql('CREATE TABLE partners_commission_rates (partner_id INT NOT NULL, commission_rate_id INT NOT NULL, PRIMARY KEY(partner_id, commission_rate_id))');
        $this->addSql('CREATE INDEX IDX_4EFF22B49393F8FE ON partners_commission_rates (partner_id)');
        $this->addSql('CREATE INDEX IDX_4EFF22B4154C794F ON partners_commission_rates (commission_rate_id)');
        $this->addSql('CREATE TABLE employee_roles (id INT NOT NULL, employee_id INT NOT NULL, role_name VARCHAR(254) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E3323BE8C03F15C ON employee_roles (employee_id)');
        $this->addSql('COMMENT ON COLUMN employee_roles.role_name IS \'(DC2Type:role_enum)\'');
        $this->addSql('CREATE TABLE tariff_rates (id INT NOT NULL, is_based_on_id INT DEFAULT NULL, page_id INT DEFAULT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, contract_types JSONB NOT NULL, customizable BOOLEAN DEFAULT NULL, description TEXT DEFAULT NULL, internal_use_only BOOLEAN DEFAULT NULL, name TEXT DEFAULT NULL, remark VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(254) NOT NULL, tariff_rate_number VARCHAR(128) NOT NULL, used_in JSONB NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, inventory_level_max_value SMALLINT DEFAULT NULL, inventory_level_min_value SMALLINT DEFAULT NULL, inventory_level_unit_code TEXT DEFAULT NULL, inventory_level_value SMALLINT DEFAULT NULL, min_contract_term_max_value SMALLINT DEFAULT NULL, min_contract_term_min_value SMALLINT DEFAULT NULL, min_contract_term_unit_code TEXT DEFAULT NULL, min_contract_term_value SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4E7361A66E363BB ON tariff_rates (is_based_on_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E7361A6C4663E4 ON tariff_rates (page_id)');
        $this->addSql('CREATE INDEX IDX_4E7361A63414710B ON tariff_rates (agent_id)');
        $this->addSql('CREATE INDEX IDX_4E7361A661220EA6 ON tariff_rates (creator_id)');
        $this->addSql('CREATE INDEX IDX_4E7361A6F6144F0A ON tariff_rates (tariff_rate_number)');
        $this->addSql('COMMENT ON COLUMN tariff_rates.status IS \'(DC2Type:tariff_rate_status_enum)\'');
        $this->addSql('CREATE TABLE phone_contact_activities (id INT NOT NULL, direction VARCHAR(254) NOT NULL, recipient_telephone_number VARCHAR(35) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN phone_contact_activities.direction IS \'(DC2Type:call_direction_enum)\'');
        $this->addSql('COMMENT ON COLUMN phone_contact_activities.recipient_telephone_number IS \'(DC2Type:phone_number)\'');
        $this->addSql('CREATE TABLE contracts (id INT NOT NULL, customer_id INT NOT NULL, refundee_id INT DEFAULT NULL, tariff_rate_id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, acquired_from_id INT DEFAULT NULL, contract_number VARCHAR(128) NOT NULL, deposit_refund_type VARCHAR(254) DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ebs_account_number VARCHAR(254) DEFAULT NULL, giro_option BOOLEAN DEFAULT NULL, meter_type VARCHAR(254) DEFAULT NULL, mssl_account_number VARCHAR(254) DEFAULT NULL, remark VARCHAR(255) DEFAULT NULL, self_read_meter_option BOOLEAN DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(254) NOT NULL, subtype VARCHAR(254) NOT NULL, type VARCHAR(254) NOT NULL, source VARCHAR(254) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, average_consumption_max_value SMALLINT DEFAULT NULL, average_consumption_min_value SMALLINT DEFAULT NULL, average_consumption_unit_code TEXT DEFAULT NULL, average_consumption_value SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_950A973AAD0FA19 ON contracts (contract_number)');
        $this->addSql('CREATE INDEX IDX_950A9739395C3F3 ON contracts (customer_id)');
        $this->addSql('CREATE INDEX IDX_950A973BD086BEA ON contracts (refundee_id)');
        $this->addSql('CREATE INDEX IDX_950A9734C86DC06 ON contracts (tariff_rate_id)');
        $this->addSql('CREATE INDEX IDX_950A9733414710B ON contracts (agent_id)');
        $this->addSql('CREATE INDEX IDX_950A97361220EA6 ON contracts (creator_id)');
        $this->addSql('CREATE INDEX IDX_950A973B43AA055 ON contracts (acquired_from_id)');
        $this->addSql('COMMENT ON COLUMN contracts.deposit_refund_type IS \'(DC2Type:refund_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN contracts.meter_type IS \'(DC2Type:meter_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN contracts.status IS \'(DC2Type:contract_status_enum)\'');
        $this->addSql('COMMENT ON COLUMN contracts.subtype IS \'(DC2Type:contract_subtype_enum)\'');
        $this->addSql('COMMENT ON COLUMN contracts.type IS \'(DC2Type:contract_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN contracts.source IS \'(DC2Type:source_enum)\'');
        $this->addSql('CREATE TABLE contracts_contract_actions (contract_id INT NOT NULL, action_id INT NOT NULL, PRIMARY KEY(contract_id, action_id))');
        $this->addSql('CREATE INDEX IDX_2580EF412576E0FD ON contracts_contract_actions (contract_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2580EF419D32F035 ON contracts_contract_actions (action_id)');
        $this->addSql('CREATE TABLE contracts_postal_addresses (contract_id INT NOT NULL, address_id INT NOT NULL, PRIMARY KEY(contract_id, address_id))');
        $this->addSql('CREATE INDEX IDX_C954053D2576E0FD ON contracts_postal_addresses (contract_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C954053DF5B7AF75 ON contracts_postal_addresses (address_id)');
        $this->addSql('CREATE TABLE contracts_digital_documents (contract_id INT NOT NULL, file_id INT NOT NULL, PRIMARY KEY(contract_id, file_id))');
        $this->addSql('CREATE INDEX IDX_EDA7ECD22576E0FD ON contracts_digital_documents (contract_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EDA7ECD293CB796C ON contracts_digital_documents (file_id)');
        $this->addSql('CREATE TABLE application_requests (id INT NOT NULL, contract_id INT DEFAULT NULL, customer_id INT NOT NULL, refundee_id INT DEFAULT NULL, tariff_rate_id INT DEFAULT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, acquired_from_id INT DEFAULT NULL, application_request_number VARCHAR(128) NOT NULL, contract_subtype VARCHAR(254) NOT NULL, contract_type VARCHAR(254) NOT NULL, deposit_refund_type VARCHAR(254) DEFAULT NULL, ebs_account_number VARCHAR(254) DEFAULT NULL, giro_option BOOLEAN DEFAULT NULL, meter_type VARCHAR(254) DEFAULT NULL, mssl_account_number VARCHAR(254) DEFAULT NULL, preferred_end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, preferred_start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, remark VARCHAR(255) DEFAULT NULL, self_read_meter_option BOOLEAN DEFAULT NULL, status VARCHAR(254) NOT NULL, type VARCHAR(254) NOT NULL, source VARCHAR(254) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, average_consumption_max_value SMALLINT DEFAULT NULL, average_consumption_min_value SMALLINT DEFAULT NULL, average_consumption_unit_code TEXT DEFAULT NULL, average_consumption_value SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C4BE0942BA06829F ON application_requests (application_request_number)');
        $this->addSql('CREATE INDEX IDX_C4BE09422576E0FD ON application_requests (contract_id)');
        $this->addSql('CREATE INDEX IDX_C4BE09429395C3F3 ON application_requests (customer_id)');
        $this->addSql('CREATE INDEX IDX_C4BE0942BD086BEA ON application_requests (refundee_id)');
        $this->addSql('CREATE INDEX IDX_C4BE09424C86DC06 ON application_requests (tariff_rate_id)');
        $this->addSql('CREATE INDEX IDX_C4BE09423414710B ON application_requests (agent_id)');
        $this->addSql('CREATE INDEX IDX_C4BE094261220EA6 ON application_requests (creator_id)');
        $this->addSql('CREATE INDEX IDX_C4BE0942B43AA055 ON application_requests (acquired_from_id)');
        $this->addSql('COMMENT ON COLUMN application_requests.contract_subtype IS \'(DC2Type:contract_subtype_enum)\'');
        $this->addSql('COMMENT ON COLUMN application_requests.contract_type IS \'(DC2Type:contract_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN application_requests.deposit_refund_type IS \'(DC2Type:refund_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN application_requests.meter_type IS \'(DC2Type:meter_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN application_requests.status IS \'(DC2Type:application_request_status_enum)\'');
        $this->addSql('COMMENT ON COLUMN application_requests.type IS \'(DC2Type:application_request_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN application_requests.source IS \'(DC2Type:source_enum)\'');
        $this->addSql('CREATE TABLE application_requests_postal_addresses (application_request_id INT NOT NULL, address_id INT NOT NULL, PRIMARY KEY(application_request_id, address_id))');
        $this->addSql('CREATE INDEX IDX_A838361535FD8949 ON application_requests_postal_addresses (application_request_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A8383615F5B7AF75 ON application_requests_postal_addresses (address_id)');
        $this->addSql('CREATE TABLE application_requests_digital_documents (application_request_id INT NOT NULL, file_id INT NOT NULL, PRIMARY KEY(application_request_id, file_id))');
        $this->addSql('CREATE INDEX IDX_D873281B35FD8949 ON application_requests_digital_documents (application_request_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D873281B93CB796C ON application_requests_digital_documents (file_id)');
        $this->addSql('CREATE TABLE leads (id INT NOT NULL, assignee_id INT DEFAULT NULL, assignor_id INT DEFAULT NULL, corporation_details_id INT DEFAULT NULL, person_details_id INT DEFAULT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, acquired_from_id INT DEFAULT NULL, contract_subtype VARCHAR(254) DEFAULT NULL, contract_type VARCHAR(254) DEFAULT NULL, date_followed_up TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, do_not_contact BOOLEAN DEFAULT NULL, existing_customer BOOLEAN DEFAULT NULL, lead_number VARCHAR(128) DEFAULT NULL, meter_type VARCHAR(254) DEFAULT NULL, preferred_contact_method VARCHAR(254) DEFAULT NULL, score VARCHAR(254) DEFAULT NULL, status VARCHAR(254) NOT NULL, type VARCHAR(254) NOT NULL, source VARCHAR(254) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, average_consumption_max_value SMALLINT DEFAULT NULL, average_consumption_min_value SMALLINT DEFAULT NULL, average_consumption_unit_code TEXT DEFAULT NULL, average_consumption_value SMALLINT DEFAULT NULL, purchase_time_frame_max_value SMALLINT DEFAULT NULL, purchase_time_frame_min_value SMALLINT DEFAULT NULL, purchase_time_frame_unit_code TEXT DEFAULT NULL, purchase_time_frame_value SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17904552EBF16628 ON leads (lead_number)');
        $this->addSql('CREATE INDEX IDX_1790455259EC7D60 ON leads (assignee_id)');
        $this->addSql('CREATE INDEX IDX_17904552DE920AE7 ON leads (assignor_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1790455242F6D1D6 ON leads (corporation_details_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_179045528DA16437 ON leads (person_details_id)');
        $this->addSql('CREATE INDEX IDX_179045523414710B ON leads (agent_id)');
        $this->addSql('CREATE INDEX IDX_1790455261220EA6 ON leads (creator_id)');
        $this->addSql('CREATE INDEX IDX_17904552B43AA055 ON leads (acquired_from_id)');
        $this->addSql('CREATE INDEX IDX_17904552EBF16628 ON leads (lead_number)');
        $this->addSql('COMMENT ON COLUMN leads.contract_subtype IS \'(DC2Type:contract_subtype_enum)\'');
        $this->addSql('COMMENT ON COLUMN leads.contract_type IS \'(DC2Type:contract_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN leads.meter_type IS \'(DC2Type:meter_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN leads.preferred_contact_method IS \'(DC2Type:contact_method_enum)\'');
        $this->addSql('COMMENT ON COLUMN leads.score IS \'(DC2Type:lead_score_enum)\'');
        $this->addSql('COMMENT ON COLUMN leads.status IS \'(DC2Type:lead_status_enum)\'');
        $this->addSql('COMMENT ON COLUMN leads.type IS \'(DC2Type:account_type_enum)\'');
        $this->addSql('COMMENT ON COLUMN leads.source IS \'(DC2Type:source_enum)\'');
        $this->addSql('CREATE TABLE leads_activities (lead_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(lead_id, activity_id))');
        $this->addSql('CREATE INDEX IDX_32108D9055458D ON leads_activities (lead_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_32108D9081C06096 ON leads_activities (activity_id)');
        $this->addSql('CREATE TABLE leads_postal_addresses (lead_id INT NOT NULL, address_id INT NOT NULL, PRIMARY KEY(lead_id, address_id))');
        $this->addSql('CREATE INDEX IDX_8B9AAD1555458D ON leads_postal_addresses (lead_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B9AAD15F5B7AF75 ON leads_postal_addresses (address_id)');
        $this->addSql('CREATE TABLE leads_notes (lead_id INT NOT NULL, note_id INT NOT NULL, PRIMARY KEY(lead_id, note_id))');
        $this->addSql('CREATE INDEX IDX_FE5F608455458D ON leads_notes (lead_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE5F608426ED0855 ON leads_notes (note_id)');
        $this->addSql('CREATE TABLE running_numbers (type VARCHAR(255) NOT NULL, series VARCHAR(255) NOT NULL, number INT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(type, series))');
        $this->addSql('CREATE UNIQUE INDEX idx_unq_type_series ON running_numbers (type, series)');
        $this->addSql('CREATE TABLE contact_points (id INT NOT NULL, contact_type TEXT DEFAULT NULL, emails JSONB NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE contact_points_fax_phone_number_roles (contact_point_id INT NOT NULL, fax_number_id INT NOT NULL, PRIMARY KEY(contact_point_id, fax_number_id))');
        $this->addSql('CREATE INDEX IDX_9CC9681A5A0D5235 ON contact_points_fax_phone_number_roles (contact_point_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9CC9681AC8C3C7AB ON contact_points_fax_phone_number_roles (fax_number_id)');
        $this->addSql('CREATE TABLE contact_points_mobile_phone_number_roles (contact_point_id INT NOT NULL, mobile_phone_number_id INT NOT NULL, PRIMARY KEY(contact_point_id, mobile_phone_number_id))');
        $this->addSql('CREATE INDEX IDX_4743C9E25A0D5235 ON contact_points_mobile_phone_number_roles (contact_point_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4743C9E2B3CDC41A ON contact_points_mobile_phone_number_roles (mobile_phone_number_id)');
        $this->addSql('CREATE TABLE contact_points_telephone_number_roles (contact_point_id INT NOT NULL, telephone_number_id INT NOT NULL, PRIMARY KEY(contact_point_id, telephone_number_id))');
        $this->addSql('CREATE INDEX IDX_EF6FF9765A0D5235 ON contact_points_telephone_number_roles (contact_point_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EF6FF976376750D ON contact_points_telephone_number_roles (telephone_number_id)');
        $this->addSql('CREATE TABLE contract_actions (id INT NOT NULL, object_id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, action_status VARCHAR(254) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, entity_type VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D198C27232D562B ON contract_actions (object_id)');
        $this->addSql('CREATE INDEX IDX_D198C273414710B ON contract_actions (agent_id)');
        $this->addSql('CREATE INDEX IDX_D198C2761220EA6 ON contract_actions (creator_id)');
        $this->addSql('COMMENT ON COLUMN contract_actions.action_status IS \'(DC2Type:action_status_enum)\'');
        $this->addSql('CREATE TABLE update_contract_actions (id INT NOT NULL, type VARCHAR(254) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN update_contract_actions.type IS \'(DC2Type:contract_action_type_enum)\'');
        $this->addSql('CREATE TABLE postal_addresses (id INT NOT NULL, address_country VARCHAR(2) DEFAULT NULL, address_locality TEXT DEFAULT NULL, address_region TEXT DEFAULT NULL, building_name TEXT DEFAULT NULL, floor TEXT DEFAULT NULL, house_number TEXT DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, street_address TEXT DEFAULT NULL, type VARCHAR(254) NOT NULL, unit_number TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN postal_addresses.type IS \'(DC2Type:postal_address_type_enum)\'');
        $this->addSql('CREATE TABLE digital_documents (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, content_path TEXT DEFAULT NULL, name TEXT DEFAULT NULL, text TEXT DEFAULT NULL, url TEXT DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_495EB1DC3414710B ON digital_documents (agent_id)');
        $this->addSql('CREATE INDEX IDX_495EB1DC61220EA6 ON digital_documents (creator_id)');
        $this->addSql('CREATE TABLE phone_number_roles (id INT NOT NULL, phone_number VARCHAR(35) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN phone_number_roles.phone_number IS \'(DC2Type:phone_number)\'');
        $this->addSql('CREATE TABLE people (id INT NOT NULL, additional_name TEXT DEFAULT NULL, alternate_name TEXT DEFAULT NULL, birth_date DATE DEFAULT NULL, birth_place TEXT DEFAULT NULL, death_date DATE DEFAULT NULL, death_place TEXT DEFAULT NULL, description TEXT DEFAULT NULL, family_name TEXT DEFAULT NULL, gender VARCHAR(254) DEFAULT NULL, given_name TEXT DEFAULT NULL, honorific_prefix TEXT DEFAULT NULL, job_title TEXT DEFAULT NULL, name TEXT DEFAULT NULL, nationality TEXT DEFAULT NULL, same_as_urls JSONB NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN people.gender IS \'(DC2Type:gender_type_enum)\'');
        $this->addSql('CREATE TABLE people_contact_points (person_id INT NOT NULL, contact_point_id INT NOT NULL, PRIMARY KEY(person_id, contact_point_id))');
        $this->addSql('CREATE INDEX IDX_955B8FF8217BBB47 ON people_contact_points (person_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_955B8FF85A0D5235 ON people_contact_points (contact_point_id)');
        $this->addSql('CREATE TABLE people_identifications (person_id INT NOT NULL, identification_id INT NOT NULL, PRIMARY KEY(person_id, identification_id))');
        $this->addSql('CREATE INDEX IDX_EBF7606217BBB47 ON people_identifications (person_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EBF76064DFE3A85 ON people_identifications (identification_id)');
        $this->addSql('CREATE TABLE commission_rates (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, category VARCHAR(254) NOT NULL, description TEXT DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name TEXT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(254) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value_max_value SMALLINT DEFAULT NULL, value_min_value SMALLINT DEFAULT NULL, value_unit_code TEXT DEFAULT NULL, value_value SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A95B9AF3414710B ON commission_rates (agent_id)');
        $this->addSql('CREATE INDEX IDX_A95B9AF61220EA6 ON commission_rates (creator_id)');
        $this->addSql('COMMENT ON COLUMN commission_rates.category IS \'(DC2Type:commission_category_enum)\'');
        $this->addSql('COMMENT ON COLUMN commission_rates.type IS \'(DC2Type:commission_type_enum)\'');
        $this->addSql('CREATE TABLE web_pages (id INT NOT NULL, image_id INT DEFAULT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, description TEXT DEFAULT NULL, disambiguating_description TEXT DEFAULT NULL, status VARCHAR(254) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ED67E1EB3DA5256D ON web_pages (image_id)');
        $this->addSql('CREATE INDEX IDX_ED67E1EB3414710B ON web_pages (agent_id)');
        $this->addSql('CREATE INDEX IDX_ED67E1EB61220EA6 ON web_pages (creator_id)');
        $this->addSql('COMMENT ON COLUMN web_pages.status IS \'(DC2Type:web_page_status_enum)\'');
        $this->addSql('CREATE TABLE create_contract_actions (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE corporations (id INT NOT NULL, description TEXT DEFAULT NULL, dissolution_date DATE DEFAULT NULL, founding_date DATE DEFAULT NULL, industry VARCHAR(254) DEFAULT NULL, legal_name TEXT DEFAULT NULL, name TEXT DEFAULT NULL, same_as_urls JSONB NOT NULL, url TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6F3B37C75E237E06 ON corporations (name)');
        $this->addSql('COMMENT ON COLUMN corporations.industry IS \'(DC2Type:industry_enum)\'');
        $this->addSql('CREATE TABLE corporations_contact_points (corporation_id INT NOT NULL, contact_point_id INT NOT NULL, PRIMARY KEY(corporation_id, contact_point_id))');
        $this->addSql('CREATE INDEX IDX_412F7AB2685369 ON corporations_contact_points (corporation_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_412F7A5A0D5235 ON corporations_contact_points (contact_point_id)');
        $this->addSql('CREATE TABLE corporations_employee_roles (corporation_id INT NOT NULL, employee_role_id INT NOT NULL, PRIMARY KEY(corporation_id, employee_role_id))');
        $this->addSql('CREATE INDEX IDX_E95AB56CB2685369 ON corporations_employee_roles (corporation_id)');
        $this->addSql('CREATE INDEX IDX_E95AB56C564F74A3 ON corporations_employee_roles (employee_role_id)');
        $this->addSql('CREATE TABLE corporations_identifications (corporation_id INT NOT NULL, identification_id INT NOT NULL, PRIMARY KEY(corporation_id, identification_id))');
        $this->addSql('CREATE INDEX IDX_D9C8EAAB2685369 ON corporations_identifications (corporation_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D9C8EAA4DFE3A85 ON corporations_identifications (identification_id)');
        $this->addSql('CREATE TABLE customer_account_postal_addresses (id INT NOT NULL, address_id INT NOT NULL, customer_account_id INT NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AAD553BCF5B7AF75 ON customer_account_postal_addresses (address_id)');
        $this->addSql('CREATE INDEX IDX_AAD553BC66A25B38 ON customer_account_postal_addresses (customer_account_id)');
        $this->addSql('CREATE TABLE customer_accounts (id INT NOT NULL, corporation_details_id INT DEFAULT NULL, partner_details_id INT DEFAULT NULL, person_details_id INT DEFAULT NULL, user_id INT DEFAULT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, account_number VARCHAR(128) NOT NULL, categories JSONB NOT NULL, do_not_contact BOOLEAN DEFAULT NULL, external_customer_number TEXT DEFAULT NULL, preferred_contact_method VARCHAR(254) DEFAULT NULL, preferred_language TEXT DEFAULT NULL, type VARCHAR(254) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E60DDD83B1A4D127 ON customer_accounts (account_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E60DDD8342F6D1D6 ON customer_accounts (corporation_details_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E60DDD83A1EB04C4 ON customer_accounts (partner_details_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E60DDD838DA16437 ON customer_accounts (person_details_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E60DDD83A76ED395 ON customer_accounts (user_id)');
        $this->addSql('CREATE INDEX IDX_E60DDD833414710B ON customer_accounts (agent_id)');
        $this->addSql('CREATE INDEX IDX_E60DDD8361220EA6 ON customer_accounts (creator_id)');
        $this->addSql('CREATE INDEX IDX_E60DDD83B1A4D127 ON customer_accounts (account_number)');
        $this->addSql('COMMENT ON COLUMN customer_accounts.preferred_contact_method IS \'(DC2Type:contact_method_enum)\'');
        $this->addSql('COMMENT ON COLUMN customer_accounts.type IS \'(DC2Type:account_type_enum)\'');
        $this->addSql('CREATE TABLE customer_accounts_notes (lead_id INT NOT NULL, note_id INT NOT NULL, PRIMARY KEY(lead_id, note_id))');
        $this->addSql('CREATE INDEX IDX_3D67E34155458D ON customer_accounts_notes (lead_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D67E34126ED0855 ON customer_accounts_notes (note_id)');
        $this->addSql('CREATE TABLE customer_accounts_customer_account_relationships (customer_account_id INT NOT NULL, relationship_id INT NOT NULL, PRIMARY KEY(customer_account_id, relationship_id))');
        $this->addSql('CREATE INDEX IDX_6C4532AE66A25B38 ON customer_accounts_customer_account_relationships (customer_account_id)');
        $this->addSql('CREATE INDEX IDX_6C4532AE2C41D668 ON customer_accounts_customer_account_relationships (relationship_id)');
        $this->addSql('CREATE TABLE customer_account_relationships (id INT NOT NULL, contract_id INT DEFAULT NULL, from_id INT NOT NULL, to_id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, type VARCHAR(254) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4B2CCB82576E0FD ON customer_account_relationships (contract_id)');
        $this->addSql('CREATE INDEX IDX_4B2CCB878CED90B ON customer_account_relationships (from_id)');
        $this->addSql('CREATE INDEX IDX_4B2CCB830354A65 ON customer_account_relationships (to_id)');
        $this->addSql('CREATE INDEX IDX_4B2CCB83414710B ON customer_account_relationships (agent_id)');
        $this->addSql('CREATE INDEX IDX_4B2CCB861220EA6 ON customer_account_relationships (creator_id)');
        $this->addSql('COMMENT ON COLUMN customer_account_relationships.type IS \'(DC2Type:customer_relationship_type_enum)\'');
        $this->addSql('CREATE TABLE email_activities (id INT NOT NULL, about VARCHAR(254) DEFAULT NULL, bcc_recipients JSONB NOT NULL, cc_recipients JSONB NOT NULL, template TEXT DEFAULT NULL, to_recipients JSONB NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE email_activities_digital_documents (email_activity_id INT NOT NULL, file_id INT NOT NULL, PRIMARY KEY(email_activity_id, file_id))');
        $this->addSql('CREATE INDEX IDX_27FC22B997001C21 ON email_activities_digital_documents (email_activity_id)');
        $this->addSql('CREATE INDEX IDX_27FC22B993CB796C ON email_activities_digital_documents (file_id)');
        $this->addSql('CREATE TABLE notes (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, text TEXT DEFAULT NULL, type VARCHAR(254) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_11BA68C3414710B ON notes (agent_id)');
        $this->addSql('CREATE INDEX IDX_11BA68C61220EA6 ON notes (creator_id)');
        $this->addSql('COMMENT ON COLUMN notes.type IS \'(DC2Type:note_type_enum)\'');
        $this->addSql('CREATE TABLE notes_digital_documents (note_id INT NOT NULL, file_id INT NOT NULL, PRIMARY KEY(note_id, file_id))');
        $this->addSql('CREATE INDEX IDX_175186626ED0855 ON notes_digital_documents (note_id)');
        $this->addSql('CREATE INDEX IDX_175186693CB796C ON notes_digital_documents (file_id)');
        $this->addSql('CREATE TABLE identifications (id INT NOT NULL, agent_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, description TEXT DEFAULT NULL, name VARCHAR(254) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_through TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value TEXT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_65F654C43414710B ON identifications (agent_id)');
        $this->addSql('CREATE INDEX IDX_65F654C461220EA6 ON identifications (creator_id)');
        $this->addSql('CREATE INDEX IDX_65F654C45E237E06 ON identifications (name)');
        $this->addSql('CREATE INDEX IDX_65F654C41D775834 ON identifications (value)');
        $this->addSql('COMMENT ON COLUMN identifications.name IS \'(DC2Type:identification_name_enum)\'');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE53414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE561220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sms_activities ADD CONSTRAINT FK_E083E80CBF396750 FOREIGN KEY (id) REFERENCES activities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partners ADD CONSTRAINT FK_EFEB51644B09E92C FOREIGN KEY (administrator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partners_commission_rates ADD CONSTRAINT FK_4EFF22B49393F8FE FOREIGN KEY (partner_id) REFERENCES partners (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partners_commission_rates ADD CONSTRAINT FK_4EFF22B4154C794F FOREIGN KEY (commission_rate_id) REFERENCES commission_rates (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE employee_roles ADD CONSTRAINT FK_5E3323BE8C03F15C FOREIGN KEY (employee_id) REFERENCES customer_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tariff_rates ADD CONSTRAINT FK_4E7361A66E363BB FOREIGN KEY (is_based_on_id) REFERENCES tariff_rates (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tariff_rates ADD CONSTRAINT FK_4E7361A6C4663E4 FOREIGN KEY (page_id) REFERENCES web_pages (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tariff_rates ADD CONSTRAINT FK_4E7361A63414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tariff_rates ADD CONSTRAINT FK_4E7361A661220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE phone_contact_activities ADD CONSTRAINT FK_21937250BF396750 FOREIGN KEY (id) REFERENCES activities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts ADD CONSTRAINT FK_950A9739395C3F3 FOREIGN KEY (customer_id) REFERENCES customer_accounts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts ADD CONSTRAINT FK_950A973BD086BEA FOREIGN KEY (refundee_id) REFERENCES customer_accounts (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts ADD CONSTRAINT FK_950A9734C86DC06 FOREIGN KEY (tariff_rate_id) REFERENCES tariff_rates (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts ADD CONSTRAINT FK_950A9733414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts ADD CONSTRAINT FK_950A97361220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts ADD CONSTRAINT FK_950A973B43AA055 FOREIGN KEY (acquired_from_id) REFERENCES customer_accounts (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_contract_actions ADD CONSTRAINT FK_2580EF412576E0FD FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_contract_actions ADD CONSTRAINT FK_2580EF419D32F035 FOREIGN KEY (action_id) REFERENCES contract_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_postal_addresses ADD CONSTRAINT FK_C954053D2576E0FD FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_postal_addresses ADD CONSTRAINT FK_C954053DF5B7AF75 FOREIGN KEY (address_id) REFERENCES postal_addresses (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_digital_documents ADD CONSTRAINT FK_EDA7ECD22576E0FD FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_digital_documents ADD CONSTRAINT FK_EDA7ECD293CB796C FOREIGN KEY (file_id) REFERENCES digital_documents (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests ADD CONSTRAINT FK_C4BE09422576E0FD FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests ADD CONSTRAINT FK_C4BE09429395C3F3 FOREIGN KEY (customer_id) REFERENCES customer_accounts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests ADD CONSTRAINT FK_C4BE0942BD086BEA FOREIGN KEY (refundee_id) REFERENCES customer_accounts (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests ADD CONSTRAINT FK_C4BE09424C86DC06 FOREIGN KEY (tariff_rate_id) REFERENCES tariff_rates (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests ADD CONSTRAINT FK_C4BE09423414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests ADD CONSTRAINT FK_C4BE094261220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests ADD CONSTRAINT FK_C4BE0942B43AA055 FOREIGN KEY (acquired_from_id) REFERENCES customer_accounts (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests_postal_addresses ADD CONSTRAINT FK_A838361535FD8949 FOREIGN KEY (application_request_id) REFERENCES application_requests (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests_postal_addresses ADD CONSTRAINT FK_A8383615F5B7AF75 FOREIGN KEY (address_id) REFERENCES postal_addresses (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests_digital_documents ADD CONSTRAINT FK_D873281B35FD8949 FOREIGN KEY (application_request_id) REFERENCES application_requests (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_requests_digital_documents ADD CONSTRAINT FK_D873281B93CB796C FOREIGN KEY (file_id) REFERENCES digital_documents (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_1790455259EC7D60 FOREIGN KEY (assignee_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_17904552DE920AE7 FOREIGN KEY (assignor_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_1790455242F6D1D6 FOREIGN KEY (corporation_details_id) REFERENCES corporations (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_179045528DA16437 FOREIGN KEY (person_details_id) REFERENCES people (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_179045523414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_1790455261220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_17904552B43AA055 FOREIGN KEY (acquired_from_id) REFERENCES customer_accounts (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads_activities ADD CONSTRAINT FK_32108D9055458D FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads_activities ADD CONSTRAINT FK_32108D9081C06096 FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads_postal_addresses ADD CONSTRAINT FK_8B9AAD1555458D FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads_postal_addresses ADD CONSTRAINT FK_8B9AAD15F5B7AF75 FOREIGN KEY (address_id) REFERENCES postal_addresses (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads_notes ADD CONSTRAINT FK_FE5F608455458D FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads_notes ADD CONSTRAINT FK_FE5F608426ED0855 FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contact_points_fax_phone_number_roles ADD CONSTRAINT FK_9CC9681A5A0D5235 FOREIGN KEY (contact_point_id) REFERENCES contact_points (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contact_points_fax_phone_number_roles ADD CONSTRAINT FK_9CC9681AC8C3C7AB FOREIGN KEY (fax_number_id) REFERENCES phone_number_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contact_points_mobile_phone_number_roles ADD CONSTRAINT FK_4743C9E25A0D5235 FOREIGN KEY (contact_point_id) REFERENCES contact_points (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contact_points_mobile_phone_number_roles ADD CONSTRAINT FK_4743C9E2B3CDC41A FOREIGN KEY (mobile_phone_number_id) REFERENCES phone_number_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contact_points_telephone_number_roles ADD CONSTRAINT FK_EF6FF9765A0D5235 FOREIGN KEY (contact_point_id) REFERENCES contact_points (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contact_points_telephone_number_roles ADD CONSTRAINT FK_EF6FF976376750D FOREIGN KEY (telephone_number_id) REFERENCES phone_number_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contract_actions ADD CONSTRAINT FK_D198C27232D562B FOREIGN KEY (object_id) REFERENCES contracts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contract_actions ADD CONSTRAINT FK_D198C273414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contract_actions ADD CONSTRAINT FK_D198C2761220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE update_contract_actions ADD CONSTRAINT FK_C0E7AD26BF396750 FOREIGN KEY (id) REFERENCES contract_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE digital_documents ADD CONSTRAINT FK_495EB1DC3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE digital_documents ADD CONSTRAINT FK_495EB1DC61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE people_contact_points ADD CONSTRAINT FK_955B8FF8217BBB47 FOREIGN KEY (person_id) REFERENCES people (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE people_contact_points ADD CONSTRAINT FK_955B8FF85A0D5235 FOREIGN KEY (contact_point_id) REFERENCES contact_points (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE people_identifications ADD CONSTRAINT FK_EBF7606217BBB47 FOREIGN KEY (person_id) REFERENCES people (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE people_identifications ADD CONSTRAINT FK_EBF76064DFE3A85 FOREIGN KEY (identification_id) REFERENCES identifications (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commission_rates ADD CONSTRAINT FK_A95B9AF3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commission_rates ADD CONSTRAINT FK_A95B9AF61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_pages ADD CONSTRAINT FK_ED67E1EB3DA5256D FOREIGN KEY (image_id) REFERENCES digital_documents (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_pages ADD CONSTRAINT FK_ED67E1EB3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_pages ADD CONSTRAINT FK_ED67E1EB61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE create_contract_actions ADD CONSTRAINT FK_9DD5130EBF396750 FOREIGN KEY (id) REFERENCES contract_actions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporations_contact_points ADD CONSTRAINT FK_412F7AB2685369 FOREIGN KEY (corporation_id) REFERENCES corporations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporations_contact_points ADD CONSTRAINT FK_412F7A5A0D5235 FOREIGN KEY (contact_point_id) REFERENCES contact_points (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporations_employee_roles ADD CONSTRAINT FK_E95AB56CB2685369 FOREIGN KEY (corporation_id) REFERENCES corporations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporations_employee_roles ADD CONSTRAINT FK_E95AB56C564F74A3 FOREIGN KEY (employee_role_id) REFERENCES employee_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporations_identifications ADD CONSTRAINT FK_D9C8EAAB2685369 FOREIGN KEY (corporation_id) REFERENCES corporations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporations_identifications ADD CONSTRAINT FK_D9C8EAA4DFE3A85 FOREIGN KEY (identification_id) REFERENCES identifications (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_account_postal_addresses ADD CONSTRAINT FK_AAD553BCF5B7AF75 FOREIGN KEY (address_id) REFERENCES postal_addresses (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_account_postal_addresses ADD CONSTRAINT FK_AAD553BC66A25B38 FOREIGN KEY (customer_account_id) REFERENCES customer_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts ADD CONSTRAINT FK_E60DDD8342F6D1D6 FOREIGN KEY (corporation_details_id) REFERENCES corporations (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts ADD CONSTRAINT FK_E60DDD83A1EB04C4 FOREIGN KEY (partner_details_id) REFERENCES partners (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts ADD CONSTRAINT FK_E60DDD838DA16437 FOREIGN KEY (person_details_id) REFERENCES people (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts ADD CONSTRAINT FK_E60DDD83A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts ADD CONSTRAINT FK_E60DDD833414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts ADD CONSTRAINT FK_E60DDD8361220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts_notes ADD CONSTRAINT FK_3D67E34155458D FOREIGN KEY (lead_id) REFERENCES customer_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts_notes ADD CONSTRAINT FK_3D67E34126ED0855 FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts_customer_account_relationships ADD CONSTRAINT FK_6C4532AE66A25B38 FOREIGN KEY (customer_account_id) REFERENCES customer_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_accounts_customer_account_relationships ADD CONSTRAINT FK_6C4532AE2C41D668 FOREIGN KEY (relationship_id) REFERENCES customer_account_relationships (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_account_relationships ADD CONSTRAINT FK_4B2CCB82576E0FD FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_account_relationships ADD CONSTRAINT FK_4B2CCB878CED90B FOREIGN KEY (from_id) REFERENCES customer_accounts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_account_relationships ADD CONSTRAINT FK_4B2CCB830354A65 FOREIGN KEY (to_id) REFERENCES customer_accounts (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_account_relationships ADD CONSTRAINT FK_4B2CCB83414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_account_relationships ADD CONSTRAINT FK_4B2CCB861220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_activities ADD CONSTRAINT FK_19425D3ABF396750 FOREIGN KEY (id) REFERENCES activities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_activities_digital_documents ADD CONSTRAINT FK_27FC22B997001C21 FOREIGN KEY (email_activity_id) REFERENCES email_activities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_activities_digital_documents ADD CONSTRAINT FK_27FC22B993CB796C FOREIGN KEY (file_id) REFERENCES digital_documents (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notes ADD CONSTRAINT FK_11BA68C3414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notes ADD CONSTRAINT FK_11BA68C61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notes_digital_documents ADD CONSTRAINT FK_175186626ED0855 FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notes_digital_documents ADD CONSTRAINT FK_175186693CB796C FOREIGN KEY (file_id) REFERENCES digital_documents (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE identifications ADD CONSTRAINT FK_65F654C43414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE identifications ADD CONSTRAINT FK_65F654C461220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD agent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD creator_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE users ALTER date_created DROP NOT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E93414710B FOREIGN KEY (agent_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E961220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_1483A5E93414710B ON users (agent_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E961220EA6 ON users (creator_id)');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf('postgresql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE sms_activities DROP CONSTRAINT FK_E083E80CBF396750');
        $this->addSql('ALTER TABLE phone_contact_activities DROP CONSTRAINT FK_21937250BF396750');
        $this->addSql('ALTER TABLE leads_activities DROP CONSTRAINT FK_32108D9081C06096');
        $this->addSql('ALTER TABLE email_activities DROP CONSTRAINT FK_19425D3ABF396750');
        $this->addSql('ALTER TABLE partners_commission_rates DROP CONSTRAINT FK_4EFF22B49393F8FE');
        $this->addSql('ALTER TABLE customer_accounts DROP CONSTRAINT FK_E60DDD83A1EB04C4');
        $this->addSql('ALTER TABLE corporations_employee_roles DROP CONSTRAINT FK_E95AB56C564F74A3');
        $this->addSql('ALTER TABLE tariff_rates DROP CONSTRAINT FK_4E7361A66E363BB');
        $this->addSql('ALTER TABLE contracts DROP CONSTRAINT FK_950A9734C86DC06');
        $this->addSql('ALTER TABLE application_requests DROP CONSTRAINT FK_C4BE09424C86DC06');
        $this->addSql('ALTER TABLE contracts_contract_actions DROP CONSTRAINT FK_2580EF412576E0FD');
        $this->addSql('ALTER TABLE contracts_postal_addresses DROP CONSTRAINT FK_C954053D2576E0FD');
        $this->addSql('ALTER TABLE contracts_digital_documents DROP CONSTRAINT FK_EDA7ECD22576E0FD');
        $this->addSql('ALTER TABLE application_requests DROP CONSTRAINT FK_C4BE09422576E0FD');
        $this->addSql('ALTER TABLE contract_actions DROP CONSTRAINT FK_D198C27232D562B');
        $this->addSql('ALTER TABLE customer_account_relationships DROP CONSTRAINT FK_4B2CCB82576E0FD');
        $this->addSql('ALTER TABLE application_requests_postal_addresses DROP CONSTRAINT FK_A838361535FD8949');
        $this->addSql('ALTER TABLE application_requests_digital_documents DROP CONSTRAINT FK_D873281B35FD8949');
        $this->addSql('ALTER TABLE leads_activities DROP CONSTRAINT FK_32108D9055458D');
        $this->addSql('ALTER TABLE leads_postal_addresses DROP CONSTRAINT FK_8B9AAD1555458D');
        $this->addSql('ALTER TABLE leads_notes DROP CONSTRAINT FK_FE5F608455458D');
        $this->addSql('ALTER TABLE contact_points_fax_phone_number_roles DROP CONSTRAINT FK_9CC9681A5A0D5235');
        $this->addSql('ALTER TABLE contact_points_mobile_phone_number_roles DROP CONSTRAINT FK_4743C9E25A0D5235');
        $this->addSql('ALTER TABLE contact_points_telephone_number_roles DROP CONSTRAINT FK_EF6FF9765A0D5235');
        $this->addSql('ALTER TABLE people_contact_points DROP CONSTRAINT FK_955B8FF85A0D5235');
        $this->addSql('ALTER TABLE corporations_contact_points DROP CONSTRAINT FK_412F7A5A0D5235');
        $this->addSql('ALTER TABLE contracts_contract_actions DROP CONSTRAINT FK_2580EF419D32F035');
        $this->addSql('ALTER TABLE update_contract_actions DROP CONSTRAINT FK_C0E7AD26BF396750');
        $this->addSql('ALTER TABLE create_contract_actions DROP CONSTRAINT FK_9DD5130EBF396750');
        $this->addSql('ALTER TABLE contracts_postal_addresses DROP CONSTRAINT FK_C954053DF5B7AF75');
        $this->addSql('ALTER TABLE application_requests_postal_addresses DROP CONSTRAINT FK_A8383615F5B7AF75');
        $this->addSql('ALTER TABLE leads_postal_addresses DROP CONSTRAINT FK_8B9AAD15F5B7AF75');
        $this->addSql('ALTER TABLE customer_account_postal_addresses DROP CONSTRAINT FK_AAD553BCF5B7AF75');
        $this->addSql('ALTER TABLE contracts_digital_documents DROP CONSTRAINT FK_EDA7ECD293CB796C');
        $this->addSql('ALTER TABLE application_requests_digital_documents DROP CONSTRAINT FK_D873281B93CB796C');
        $this->addSql('ALTER TABLE web_pages DROP CONSTRAINT FK_ED67E1EB3DA5256D');
        $this->addSql('ALTER TABLE email_activities_digital_documents DROP CONSTRAINT FK_27FC22B993CB796C');
        $this->addSql('ALTER TABLE notes_digital_documents DROP CONSTRAINT FK_175186693CB796C');
        $this->addSql('ALTER TABLE contact_points_fax_phone_number_roles DROP CONSTRAINT FK_9CC9681AC8C3C7AB');
        $this->addSql('ALTER TABLE contact_points_mobile_phone_number_roles DROP CONSTRAINT FK_4743C9E2B3CDC41A');
        $this->addSql('ALTER TABLE contact_points_telephone_number_roles DROP CONSTRAINT FK_EF6FF976376750D');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_179045528DA16437');
        $this->addSql('ALTER TABLE people_contact_points DROP CONSTRAINT FK_955B8FF8217BBB47');
        $this->addSql('ALTER TABLE people_identifications DROP CONSTRAINT FK_EBF7606217BBB47');
        $this->addSql('ALTER TABLE customer_accounts DROP CONSTRAINT FK_E60DDD838DA16437');
        $this->addSql('ALTER TABLE partners_commission_rates DROP CONSTRAINT FK_4EFF22B4154C794F');
        $this->addSql('ALTER TABLE tariff_rates DROP CONSTRAINT FK_4E7361A6C4663E4');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_1790455242F6D1D6');
        $this->addSql('ALTER TABLE corporations_contact_points DROP CONSTRAINT FK_412F7AB2685369');
        $this->addSql('ALTER TABLE corporations_employee_roles DROP CONSTRAINT FK_E95AB56CB2685369');
        $this->addSql('ALTER TABLE corporations_identifications DROP CONSTRAINT FK_D9C8EAAB2685369');
        $this->addSql('ALTER TABLE customer_accounts DROP CONSTRAINT FK_E60DDD8342F6D1D6');
        $this->addSql('ALTER TABLE employee_roles DROP CONSTRAINT FK_5E3323BE8C03F15C');
        $this->addSql('ALTER TABLE contracts DROP CONSTRAINT FK_950A9739395C3F3');
        $this->addSql('ALTER TABLE contracts DROP CONSTRAINT FK_950A973BD086BEA');
        $this->addSql('ALTER TABLE contracts DROP CONSTRAINT FK_950A973B43AA055');
        $this->addSql('ALTER TABLE application_requests DROP CONSTRAINT FK_C4BE09429395C3F3');
        $this->addSql('ALTER TABLE application_requests DROP CONSTRAINT FK_C4BE0942BD086BEA');
        $this->addSql('ALTER TABLE application_requests DROP CONSTRAINT FK_C4BE0942B43AA055');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_17904552B43AA055');
        $this->addSql('ALTER TABLE customer_account_postal_addresses DROP CONSTRAINT FK_AAD553BC66A25B38');
        $this->addSql('ALTER TABLE customer_accounts_notes DROP CONSTRAINT FK_3D67E34155458D');
        $this->addSql('ALTER TABLE customer_accounts_customer_account_relationships DROP CONSTRAINT FK_6C4532AE66A25B38');
        $this->addSql('ALTER TABLE customer_account_relationships DROP CONSTRAINT FK_4B2CCB878CED90B');
        $this->addSql('ALTER TABLE customer_account_relationships DROP CONSTRAINT FK_4B2CCB830354A65');
        $this->addSql('ALTER TABLE customer_accounts_customer_account_relationships DROP CONSTRAINT FK_6C4532AE2C41D668');
        $this->addSql('ALTER TABLE email_activities_digital_documents DROP CONSTRAINT FK_27FC22B997001C21');
        $this->addSql('ALTER TABLE leads_notes DROP CONSTRAINT FK_FE5F608426ED0855');
        $this->addSql('ALTER TABLE customer_accounts_notes DROP CONSTRAINT FK_3D67E34126ED0855');
        $this->addSql('ALTER TABLE notes_digital_documents DROP CONSTRAINT FK_175186626ED0855');
        $this->addSql('ALTER TABLE people_identifications DROP CONSTRAINT FK_EBF76064DFE3A85');
        $this->addSql('ALTER TABLE corporations_identifications DROP CONSTRAINT FK_D9C8EAA4DFE3A85');
        $this->addSql('DROP SEQUENCE activities_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE partners_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE employee_roles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tariff_rates_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contracts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE application_requests_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE leads_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contact_points_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contract_actions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE postal_addresses_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE digital_documents_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE phone_number_roles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE people_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE commission_rates_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE web_pages_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE corporations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE customer_account_postal_addresses_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE customer_accounts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE customer_account_relationships_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE notes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE identifications_id_seq CASCADE');
        $this->addSql('DROP TABLE activities');
        $this->addSql('DROP TABLE sms_activities');
        $this->addSql('DROP TABLE partners');
        $this->addSql('DROP TABLE partners_commission_rates');
        $this->addSql('DROP TABLE employee_roles');
        $this->addSql('DROP TABLE tariff_rates');
        $this->addSql('DROP TABLE phone_contact_activities');
        $this->addSql('DROP TABLE contracts');
        $this->addSql('DROP TABLE contracts_contract_actions');
        $this->addSql('DROP TABLE contracts_postal_addresses');
        $this->addSql('DROP TABLE contracts_digital_documents');
        $this->addSql('DROP TABLE application_requests');
        $this->addSql('DROP TABLE application_requests_postal_addresses');
        $this->addSql('DROP TABLE application_requests_digital_documents');
        $this->addSql('DROP TABLE leads');
        $this->addSql('DROP TABLE leads_activities');
        $this->addSql('DROP TABLE leads_postal_addresses');
        $this->addSql('DROP TABLE leads_notes');
        $this->addSql('DROP TABLE running_numbers');
        $this->addSql('DROP TABLE contact_points');
        $this->addSql('DROP TABLE contact_points_fax_phone_number_roles');
        $this->addSql('DROP TABLE contact_points_mobile_phone_number_roles');
        $this->addSql('DROP TABLE contact_points_telephone_number_roles');
        $this->addSql('DROP TABLE contract_actions');
        $this->addSql('DROP TABLE update_contract_actions');
        $this->addSql('DROP TABLE postal_addresses');
        $this->addSql('DROP TABLE digital_documents');
        $this->addSql('DROP TABLE phone_number_roles');
        $this->addSql('DROP TABLE people');
        $this->addSql('DROP TABLE people_contact_points');
        $this->addSql('DROP TABLE people_identifications');
        $this->addSql('DROP TABLE commission_rates');
        $this->addSql('DROP TABLE web_pages');
        $this->addSql('DROP TABLE create_contract_actions');
        $this->addSql('DROP TABLE corporations');
        $this->addSql('DROP TABLE corporations_contact_points');
        $this->addSql('DROP TABLE corporations_employee_roles');
        $this->addSql('DROP TABLE corporations_identifications');
        $this->addSql('DROP TABLE customer_account_postal_addresses');
        $this->addSql('DROP TABLE customer_accounts');
        $this->addSql('DROP TABLE customer_accounts_notes');
        $this->addSql('DROP TABLE customer_accounts_customer_account_relationships');
        $this->addSql('DROP TABLE customer_account_relationships');
        $this->addSql('DROP TABLE email_activities');
        $this->addSql('DROP TABLE email_activities_digital_documents');
        $this->addSql('DROP TABLE notes');
        $this->addSql('DROP TABLE notes_digital_documents');
        $this->addSql('DROP TABLE identifications');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E93414710B');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E961220EA6');
        $this->addSql('DROP INDEX IDX_1483A5E93414710B');
        $this->addSql('DROP INDEX IDX_1483A5E961220EA6');
        $this->addSql('ALTER TABLE users DROP agent_id');
        $this->addSql('ALTER TABLE users DROP creator_id');
        $this->addSql('ALTER TABLE users DROP date_modified');
        $this->addSql('ALTER TABLE users ALTER date_created SET NOT NULL');
    }
}
