App\Entity\ApplicationRequest:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - applicationRequestNumber
        - App\Validator\Constraints\ApplicationRequestCustomerStatus: ~
        - App\Validator\Constraints\ApplicationRequestClosure: ~
        - App\Validator\Constraints\ApplicationRequestRenewal: ~
        # - App\Validator\Constraints\ApplicationRequestReferralCode: ~
        - App\Validator\Constraints\ApplicationRequestPromotion: ~
        - App\Validator\Constraints\ApplicationRequestTransferOut: ~
        - App\Validator\Constraints\ApplicationRequestUniquePremiseAddress: ~
    properties:
        acquirerCode:
            - Type:
                type: string
        acquirerName:
            - Type:
                type: string
        activities:
            - All:
                - Type:
                    type: App\Entity\Activity
            - Valid:
                traverse: true
        addonServices:
            - All:
                - Type:
                    type: App\Entity\AddonService
            - Valid:
                traverse: true
        addresses:
            - All:
                - Type:
                    type: App\Entity\PostalAddress
            - Valid:
                traverse: true
        advisoryNotice:
            - Type:
                type: App\Entity\AdvisoryNotice
        applicationRequestNumber:
            - Type:
                type: string
            - NotNull: ~
        averageConsumption:
            - Type:
                type: App\Entity\QuantitativeValue
            - NotNull: ~
            - Valid: ~
        billSubscriptionTypes:
            - Choice:
                callback: [App\Enum\BillSubscriptionType, keys]
                multiple: true
        contactPerson:
            - Type:
                type: App\Entity\CustomerAccount
            - NotNull: { groups: [finalized] }
        contract:
            - Type:
                type: App\Entity\Contract
        contractSubtype:
            - Type:
                type: string
        contractType:
            - Type:
                type: App\Enum\ContractType
        corporationDetails:
            - Type:
                type: App\Entity\Corporation
            - Valid:
                traverse: true
        customer:
            - Type:
                type: App\Entity\CustomerAccount
            - NotNull: { groups: [finalized] }
        customerOf:
            - Type:
                type: string
        customerRepresentative:
            - Type:
                type: App\Entity\CustomerAccount
            - Valid:
                  traverse: true
        customerType:
            - Type:
                type: App\Enum\AccountType
            - NotNull: { groups: [finalized] }
        customized:
            - Type:
                type: bool
        dateSubmitted:
            - DateTime: ~
        depositAmount:
            - Type:
                type: App\Entity\MonetaryAmount
        depositRefundType:
            - Type:
                type: App\Enum\RefundType
        ebsAccountNumber:
            - Regex:
                pattern: '/^(?!93)[0-9]{9}[0-9-]{1}$/'
        externalApplicationRequestNumber:
            - Type:
                type: string
        giroOption:
            - Type:
                type: bool
        location:
            - Type:
                type: string
        meterType:
            - Type:
                type: App\Enum\MeterType
        msslAccountNumber:
            - Regex:
                pattern: '/^(93)[0-9]{8}$/'
        paymentMode:
            - Type:
                type: App\Enum\PaymentMode
        personDetails:
            - Type:
                type: App\Entity\Person
            - Valid:
                traverse: true
        preferredEndDate:
            - DateTime: ~
        preferredStartDate:
            - DateTime: ~
        promotion:
            - Type:
                  type: App\Entity\Promotion
        quotation:
            - Type:
                type: App\Entity\Quotation
        quotationOffer:
            - Type:
                type: App\Entity\QuotationPriceConfiguration
        recurringOption:
            - Type:
                type: bool
        referralCode:
            - Type:
                type: string
        referralSource:
            - Type:
                type: App\Enum\ReferralSource
        refundee:
            - Type:
                type: App\Entity\CustomerAccount
        refundeeDetails:
            - Type:
                  type: App\Entity\Person
        remark:
            - Type:
                type: string
        representativeDetails:
            - Type:
                  type: App\Entity\Person
        salesRepName:
            - Type:
                type: string
        selfApplication:
            - Type:
                type: bool
        selfReadMeterOption:
            - Type:
                type: bool
        specifiedReferralSource:
            - Type:
                type: string
        status:
            - Type:
                type: App\Enum\ApplicationRequestStatus
            - NotNull: ~
        submitter:
            - Type:
                type: App\Entity\User
        supplementaryFiles:
            - All:
                - Type:
                    type: App\Entity\DigitalDocument
            - Valid:
                traverse: true
        tariffRate:
            - Type:
                type: App\Entity\TariffRate
            - NotNull: { groups: [finalized_contract_application] }
        terminationDate:
            - DateTime: ~
        terminationReason:
            - Type:
                type: string
        type:
            - Type:
                type: App\Enum\ApplicationRequestType
            - NotNull: ~
        urlToken:
            - Type:
                type: App\Entity\UrlToken

        # BlameableTrait
        agent:
            - Type:
                type: App\Entity\User
        creator:
            - Type:
                type: App\Entity\User

        # SourceableTrait
        acquiredFrom:
            - Type:
                type: App\Entity\CustomerAccount
        source:
            - Type:
                type: string
                # type: App\Enum\Source
        sourceUrl:
            - Url: ~

        # TimestampableTrait
        dateCreated:
            - DateTime: ~
        dateModified:
            - DateTime: ~
