App\Entity\CampaignTemplate:
    properties:
        isBasedOn:
            - Type:
                type: App\Entity\CampaignTemplate
        name:
            - Type:
                type: string
            - NotNull: ~
        rawText:
            - Type:
                type: string
            - NotNull: ~
        text:
            - Type:
                type: string
            - NotNull: ~
        thumbnailImage:
            - Type:
                type: App\Entity\DigitalDocument
