App\Entity\ContractDuration:
    properties:  
        term:
            - Type:
                type: App\Entity\QuantitativeValue
            - NotNull: ~         
        validFrom:
            - DateTime: ~  
            - NotNull: ~                   
        validThrough: 
            - DateTime: ~  
            - NotNull: ~  
        # BlameableTrait
        agent:
            - Type:
                type: App\Entity\User
        creator:
            - Type:
                type: App\Entity\User

        # TimestampableTrait
        dateCreated:
            - DateTime: ~
        dateModified:
            - DateTime: ~     
