App\Entity\ContractAction:
    properties:
        instrument:
            - Type:
                type: App\Entity\ApplicationRequest    
        actionStatus:
            - Type:
                type: App\Enum\ActionStatus
            - NotNull: ~
        object:
            - Type:
                type: App\Entity\Contract
            - NotNull: ~
        result:
            - Type:
                type: App\Entity\Contract             

        # BlameableTrait
        agent:
            - Type:
                type: App\Entity\User
        creator:
            - Type:
                type: App\Entity\User

        # TimestampableTrait
        dateCreated:
            - DateTime: ~
        dateModified:
            - DateTime: ~
