App\Entity\EarnContractCreditsAction:
    properties:
        instrument:
            - Type:
                type: App\Entity\Contract
        object:
            - Type:
                type: App\Entity\Contract
            - NotNull: ~
        scheme:
            - Type:
                type: App\Entity\CreditsScheme
        sender:
            - Type:
                type: App\Entity\CustomerAccount
