App\Entity\ItemList:
    properties:
        description:
            - Type:
                type: string
        itemListElement:
            - All:
                - Type:
                    type: App\Entity\ListItem
            - Valid:
                traverse: true
        name:
            - Type:
                type: string

        # BlameableTrait
        agent:
            - Type:
                type: App\Entity\User
        creator:
            - Type:
                type: App\Entity\User

        # TimestampableTrait
        dateCreated:
            - DateTime: ~
        dateModified:
            - DateTime: ~
