App\Entity\QuotationPostalAddress:
    properties:
        addresses:
            - All:
                - Type:
                    type: App\Entity\PostalAddress
            - Valid:
                traverse: true
        ebsAccountNumber:
            - Regex:
                pattern: '/^(?!93)[0-9]{9}[0-9-]{1}$/'            
        msslAccountNumber:
            - Regex:
                pattern: '/^(93)[0-9]{8}$/' 
        # BlameableTrait
        agent:
            - Type:
                type: App\Entity\User
        creator:
            - Type:
                type: App\Entity\User

        # TimestampableTrait
        dateCreated:
            - DateTime: ~
        dateModified:
            - DateTime: ~                       
                        
