App\Entity\RedeemCreditsAction:
    properties:
        instrument:
            - Type:
                type: App\Entity\Order
        object:
            - Type:
                type: App\Entity\Contract
                
