App\Entity\ReferralCreditsScheme:
    properties:
        referralAmount:
            - Type:
                type: App\Entity\QuantitativeValue
        refereeAmount:
            - Type:
                type: App\Entity\QuantitativeValue
