App\Entity\SmsActivity:
    properties:
        recipientMobileNumber:
            - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber: ~
            - NotNull: ~
        type:
            - Type:
                type: App\Enum\SMSType
            - NotNull: ~
