App\Entity\TransferCreditsAction:
    properties:
        object:
            - Type:
                type: App\Entity\CustomerAccount
            - NotNull: ~
        recipient:
            - Type:
                type: App\Entity\CustomerAccount
            - NotNull: ~
