App\Entity\UrlToken:
    properties:
        token:
            - Type:
                type: string
            - NotNull: ~
        validFrom:
            - DateTime: ~
        validThrough:
            - DateTime: ~
