<?php

declare(strict_types=1);

namespace App\WebService\Billing;

use App\Enum\ApplicationRequestType;

class Constants
{
    const APPLICATION_REQUEST_ACCOUNT_CLOSURE_TYPE = 'AC';
    const APPLICATION_REQUEST_CONTRACT_APPLICATION_TYPE = 'APP';
    const APPLICATION_REQUEST_GIRO_TERMINATION_TYPE = 'GT';
    const APPLICATION_REQUEST_TRANSFER_OUT_TYPE = 'TO';
    const APPLICATION_REQUEST_CONTRACT_RENEWAL_TYPE = 'RN';
    const APPLICATION_REQUEST_RCCS_TERMINATION_TYPE = 'RT';

    const APPLICATION_REQUEST_TYPE_MAP = [
        ApplicationRequestType::ACCOUNT_CLOSURE => self::APPLICATION_REQUEST_ACCOUNT_CLOSURE_TYPE,
        ApplicationRequestType::CONTRACT_APPLICATION => self::APPLICATION_REQUEST_CONTRACT_APPLICATION_TYPE,
        ApplicationRequestType::GIRO_TERMINATION => self::APPLICATION_REQUEST_GIRO_TERMINATION_TYPE,
        ApplicationRequestType::TRANSFER_OUT => self::APPLICATION_REQUEST_TRANSFER_OUT_TYPE,
        ApplicationRequestType::CONTRACT_RENEWAL => self::APPLICATION_REQUEST_CONTRACT_RENEWAL_TYPE,
        ApplicationRequestType::RCCS_TERMINATION => self::APPLICATION_REQUEST_RCCS_TERMINATION_TYPE,
    ];
}
